## 認識numpy

In [1]:
import numpy as np

In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
a = np.arange(1, 11, 1, dtype='float32') 
# just like for loop to build a few continous digital in a ndarrray 
# dtype can control its type which in this ndarray

In [3]:
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [4]:
a * 3

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.], dtype=float32)

In [5]:
a + 3

array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.], dtype=float32)

In [6]:
a.shape

(10,)

In [7]:
a = a.reshape(5, 2) # or a = a.reshape(5, -1)

In [8]:
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]], dtype=float32)

In [9]:
a.shape

(5, 2)

## 真實例子來感受numpy對於運算速度的提升

In [10]:
import time

In [11]:
def run():
    start_time = time.time()
    np_buff = np.random.randn(10000)
    list_buff = list(np_buff)
    for _ in range(1000):
        s = np.sum(np_buff)
    print('Usage time of Numpy is %f second' % (time.time() - start_time))
    start_time = time.time()
    for _ in range(1000):
        s = sum(list_buff)
    print('Usage time of not with Numpy is %f second' % (time.time() - start_time))

In [12]:
run()

Usage time of Numpy is 0.006982 second
Usage time of not with Numpy is 0.307172 second


    上述例子證實使用numpy來運算可提高效率

In [13]:
a.ndim # shape = (5, 2) -> 2D

2

In [14]:
a.T

array([[ 1.,  3.,  5.,  7.,  9.],
       [ 2.,  4.,  6.,  8., 10.]], dtype=float32)

In [15]:
a.dtype

dtype('float32')

In [16]:
a.data ##

In [17]:
buff = a.flat ##
type(buff)

numpy.flatiter

In [18]:
for i in buff: ##
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [19]:
a.size

10

In [20]:
a.itemsize # 32 bits

4

In [21]:
a.nbytes ##

40

In [22]:
a.strides ##

(8, 4)

In [23]:
a.sum(axis=1)

array([ 3.,  7., 11., 15., 19.], dtype=float32)

In [24]:
np.array([3e50, 4e46], dtype='float64')

array([3.e+50, 4.e+46])

# ndarray(Slicing)切片操作
    ndarray[start:stop:step]

1D

In [25]:
a = np.arange(10)

In [26]:
a, a[:]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [27]:
a[1:5]

array([1, 2, 3, 4])

In [28]:
a[2:8:2]

array([2, 4, 6])

In [29]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
a[:5],a[5:]

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

2D 

In [31]:
a = np.arange(20).reshape(4, 5)

In [32]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
a[1:], a[1:,2:4]

(array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[ 7,  8],
        [12, 13],
        [17, 18]]))

In [34]:
a[1:,::2]

array([[ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19]])

## 陣列擴張(Broadcasting)
    規則1：如果兩個陣列的軸數(ndim)不相同、軸數較少的陣列會加入新的軸，具體做法是在shape的【左邊】補1
    規則2：如果兩個陣列的軸數(ndim)相同，則會【一一】比對各軸的維度，若另一軸的維度匹配。萬一任一軸的維度都不是1維，則無法進行擴張，會傳回錯誤信息。

In [35]:
a = np.array([[1, 2], [5, 6]])

In [36]:
b = np.array([3, 4])

In [37]:
a.shape, b.shape

((2, 2), (2,))

In [38]:
a + b

array([[ 4,  6],
       [ 8, 10]])

In [39]:
c = np.array([[1, 2, 3], [4, 5, 6]])

In [40]:
a.shape, c.shape

((2, 2), (2, 3))

In [41]:
#a + c #error

    狀況一：(1, 4, 3) <-> (2, 4, 3)

    狀況二：(2, 1, 3) <-> (2, 4, 3)

    狀況三：(2, 4, 1) <-> (2, 4, 3)

    狀況四：(2, 1, 1) <-> (2, 4, 3)

    狀況五：(1, 1, 1) <-> (2, 4, 3)
    
    其他狀況(若任一軸的維度不同且兩者都不是1維)無法擴張運算

In [42]:
a = np.arange(24).reshape(2, 4, 3)
b = np.arange(12).reshape(1, 4, 3)

In [43]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [44]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

In [45]:
a + b, (a+b).shape

(array([[[ 0,  2,  4],
         [ 6,  8, 10],
         [12, 14, 16],
         [18, 20, 22]],
 
        [[12, 14, 16],
         [18, 20, 22],
         [24, 26, 28],
         [30, 32, 34]]]),
 (2, 4, 3))

In [48]:
b = np.arange(6).reshape(2, 1, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [49]:
b

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [47]:
a + b

array([[[ 0,  2,  4],
        [ 3,  5,  7],
        [ 6,  8, 10],
        [ 9, 11, 13]],

       [[15, 17, 19],
        [18, 20, 22],
        [21, 23, 25],
        [24, 26, 28]]])