# 陣列的儲存與讀取 - save() 與 load()

np.save(file, arr, allow_pickle=True, fix_imports=True)

np.load(file, mmap_mode=None, allow_pickle=True, fix_imports=True, encoding='ASCII)

file type : .npy, binary

In [141]:
import numpy as np

In [142]:
a = np.random.rand(1200*1000).reshape(1200, -1)
a

array([[0.68564811, 0.59074925, 0.52409275, ..., 0.21237303, 0.13779091,
        0.8702217 ],
       [0.13718706, 0.9692734 , 0.57066862, ..., 0.39969501, 0.15393687,
        0.4939711 ],
       [0.93890797, 0.85526525, 0.17935707, ..., 0.29193435, 0.74422616,
        0.89675888],
       ...,
       [0.82105537, 0.35343753, 0.15240969, ..., 0.8872634 , 0.58645936,
        0.59859669],
       [0.12249704, 0.34544702, 0.37673506, ..., 0.92308593, 0.98092524,
        0.09030762],
       [0.05224381, 0.4920884 , 0.42878644, ..., 0.04548954, 0.7770869 ,
        0.17348117]])

In [143]:
np.save('source/a', a)

In [144]:
b = np.load('source/a.npy')
b

array([[0.68564811, 0.59074925, 0.52409275, ..., 0.21237303, 0.13779091,
        0.8702217 ],
       [0.13718706, 0.9692734 , 0.57066862, ..., 0.39969501, 0.15393687,
        0.4939711 ],
       [0.93890797, 0.85526525, 0.17935707, ..., 0.29193435, 0.74422616,
        0.89675888],
       ...,
       [0.82105537, 0.35343753, 0.15240969, ..., 0.8872634 , 0.58645936,
        0.59859669],
       [0.12249704, 0.34544702, 0.37673506, ..., 0.92308593, 0.98092524,
        0.09030762],
       [0.05224381, 0.4920884 , 0.42878644, ..., 0.04548954, 0.7770869 ,
        0.17348117]])

In [145]:
b.shape

(1200, 1000)

以上缺點:無法兼容于python以外的程式語言或軟體工具

# 以文字格式儲存與讀取陣列 - savetxt() 與 loadtxt()

缺點：最高只能儲存2D的陣列

np.savetxt(fname, X, fmt, delimiter, newline, header, footer, comments, encoding)

np.loadtxt(fname, dtype, comment, delimiter, converters, skiprows, usecols, unpack, ndim, encoding)

In [146]:
import numpy as np

In [147]:
a = np.random.rand(3, 4)
a

array([[0.38251563, 0.87639315, 0.29097544, 0.46843954],
       [0.61090723, 0.25777427, 0.73009274, 0.01220844],
       [0.66506052, 0.93097831, 0.63279316, 0.83611651]])

In [148]:
np.savetxt('source/sample1.txt', a)

In [149]:
b = np.loadtxt('source/sample1.txt')
b

array([[0.38251563, 0.87639315, 0.29097544, 0.46843954],
       [0.61090723, 0.25777427, 0.73009274, 0.01220844],
       [0.66506052, 0.93097831, 0.63279316, 0.83611651]])

In [150]:
np.savetxt('source/sample1.csv', a)

In [151]:
c = np.loadtxt('source/sample1.csv')
c

array([[0.38251563, 0.87639315, 0.29097544, 0.46843954],
       [0.61090723, 0.25777427, 0.73009274, 0.01220844],
       [0.66506052, 0.93097831, 0.63279316, 0.83611651]])

In [152]:
np.savetxt('source/sample2.txt', a, delimiter=',') #請查看sample2.txt

In [153]:
#c = np.loadtxt('source/sample2.txt') #error

In [154]:
c = np.loadtxt('source/sample2.txt', delimiter=',')
c

array([[0.38251563, 0.87639315, 0.29097544, 0.46843954],
       [0.61090723, 0.25777427, 0.73009274, 0.01220844],
       [0.66506052, 0.93097831, 0.63279316, 0.83611651]])

In [155]:
np.savetxt('source/sample3.txt', a, fmt='%.2e') #請查看sample3.txt

In [156]:
np.savetxt('source/sample4.txt', a, fmt='%.2f') #請查看sample4.txt

In [157]:
np.savetxt('source/sample5.txt', a, fmt='%.3e',
          header='this is a header', footer='this is a footer') 
#請查看sample5.txt

In [158]:
np.savetxt('source/sample6.txt', a, fmt='%.3e',header='this is a header', 
           footer='this is a footer', comments='>>>') 
#請查看sample6.txt

In [159]:
np.loadtxt('source/sample4.txt')

array([[0.38, 0.88, 0.29, 0.47],
       [0.61, 0.26, 0.73, 0.01],
       [0.67, 0.93, 0.63, 0.84]])

In [160]:
np.loadtxt('source/sample4.txt', usecols=(0,2))

array([[0.38, 0.29],
       [0.61, 0.73],
       [0.67, 0.63]])

In [161]:
np.loadtxt('source/sample4.txt', skiprows=1) #skiprows=開頭前幾行

array([[0.61, 0.26, 0.73, 0.01],
       [0.67, 0.93, 0.63, 0.84]])

In [162]:
np.loadtxt('foo.csv', dtype=[('col1', 'i8'),
                             ('col2', 'S10'),
                             ('col3', 'f8'),
                             ('col4', 'S10')
                            ])

array([(18, b'female', 154.1, b'No'), (21, b'male', 172.3, b'Yes'),
       (22, b'female', 160.8, b'Yes'), (23, b'male', 190.1, b'Yes'),
       (25, b'female', 156. , b'No')],
      dtype=[('col1', '<i8'), ('col2', 'S10'), ('col3', '<f8'), ('col4', 'S10')])

In [163]:
np.loadtxt('foo.csv', dtype=[('col1', 'i8'),
                             ('col2', 'S10'),
                             ('col3', 'f8'),
                             ('col4', 'S10')
                            ], unpack=True)

[array([18, 21, 22, 23, 25], dtype=int64),
 array([b'female', b'male', b'female', b'male', b'female'], dtype='|S10'),
 array([154.1, 172.3, 160.8, 190.1, 156. ]),
 array([b'No', b'Yes', b'Yes', b'Yes', b'No'], dtype='|S10')]

In [164]:
age,gender,tall,driver_license=np.loadtxt('foo.csv', dtype=[('col1', 'i8'),
                                                                 ('col2', 'S10'),
                                                                 ('col3', 'f8'),
                                                                 ('col4', 'S10')
                                                                ], unpack=True)

In [165]:
age

array([18, 21, 22, 23, 25], dtype=int64)

In [166]:
gender

array([b'female', b'male', b'female', b'male', b'female'], dtype='|S10')

In [167]:
tall

array([154.1, 172.3, 160.8, 190.1, 156. ])

In [168]:
driver_license

array([b'No', b'Yes', b'Yes', b'Yes', b'No'], dtype='|S10')

In [169]:
def driver_license(str):
    if str == b'Yes':
        return 1
    else:
        return -1

In [170]:
def gender(str):
    if str == b'male':
        return 1
    else:
        return -1

In [171]:
np.loadtxt('foo.csv', converters={1:gender, 3:driver_license})

array([[ 18. ,  -1. , 154.1,  -1. ],
       [ 21. ,   1. , 172.3,   1. ],
       [ 22. ,  -1. , 160.8,   1. ],
       [ 23. ,   1. , 190.1,   1. ],
       [ 25. ,  -1. , 156. ,  -1. ]])

# 建立隨機亂數的陣列 - random()

np.random.rand(d0, d1, ...dn)

np.random.randint(low, high, size, dtype)

In [172]:
import numpy as np

In [173]:
np.random.rand()

0.27534036869868517

In [174]:
np.random.randint(10)

2

In [175]:
np.random.rand(2, 3)

array([[0.81681384, 0.26096324, 0.46271943],
       [0.2940405 , 0.19868471, 0.85686904]])

In [176]:
np.random.randint(10, size=(2, 3))

array([[6, 9, 7],
       [7, 5, 4]])

In [177]:
np.random.randint(5, 10, size=10)

array([6, 8, 5, 6, 8, 5, 7, 7, 8, 9])

In [178]:
#(stop - start) * np.random.rand() + start 回歸分析
(10 - 5) * np.random.rand(10) + 5

array([9.09680191, 6.646596  , 9.58068133, 9.44748915, 9.82959767,
       8.69775166, 6.92476023, 8.46621515, 5.94590758, 6.76523058])

np.random.seed(seed)

np.random模組的亂數產生器在初始化時，會使用一個整數來作爲seed

seed不變 random出來的結果就不變

In [179]:
np.random.seed(20)

In [180]:
np.random.rand()

0.5881308010772742

In [181]:
np.random.seed(20)
np.random.rand()

0.5881308010772742

np.random.choice(a, size, replace=True, p)

np.random.choice不僅可以隨機取出元素， 還可用replace來控制是否取出重複的元素

In [182]:
a = ['Python', 'Ruby', 'Java', 'C++', 'PHP']

In [183]:
np.random.seed(4002)
np.random.choice(a, 3)

array(['Java', 'Python', 'Java'], dtype='<U6')

In [184]:
np.random.seed(4002)
np.random.choice(a, 3, replace=False)

array(['PHP', 'C++', 'Ruby'], dtype='<U6')

In [185]:
np.random.seed(4002)
np.random.choice(a, 20, p=[0.75, 0.05, 0.05, 0.05, 0.1]) #各個元素的權重
# p的總和 = 1

array(['Python', 'Java', 'C++', 'Python', 'Python', 'Python', 'Python',
       'Python', 'Python', 'Python', 'Java', 'PHP', 'Python', 'Java',
       'Python', 'Python', 'Python', 'Python', 'Python', 'Python'],
      dtype='<U6')

In [186]:
np.random.seed(4002)
np.random.choice(5, 10)
# 0 ~ 5

array([2, 0, 2, 3, 0, 1, 1, 2, 1, 3])

np.random.shuffle(a)

In [187]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
np.random.shuffle(a)
a

array([9, 1, 4, 7, 2, 3, 0, 6, 5, 8])