# 陣列重塑 - reshape(), resize()

np.reshape(a, newshape, order='C')

order:'C','F','A'

In [1]:
import numpy as np

In [2]:
a = np.arange(12)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b = np.reshape(a, (3, 4)) # b = np.reshape(a, (3, 4), order='C') 
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
b[0, 1] = 100
b

array([[  0, 100,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

    先前的a也修改了

In [6]:
a

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

    F:Fortran, C:C語言
    他們之間的存放空間方式不同
    C:Row-major order
    F:Column-major order

In [7]:
c = np.arange(12)
d = np.reshape(c, (3, 4), order='F')
d

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [8]:
#a = np.reshape(c, (3, 5)) # error

In [9]:
a = np.reshape(c, (3, -1))
b = np.reshape(c, (-1, 2))
a, b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]))

np.resize(a, newshape)

In [10]:
a = np.arange(12)

In [11]:
np.reshape(a, (3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np.resize(a, (3, 2)) 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
np.resize(a, (3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11,  0,  1,  2]])

In [14]:
b = np.resize(a, (3, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

    此方法不會更改到原先的a

In [15]:
b[0, 1] = 100
a, b

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[  0, 100,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]]))

# 在陣列最後面加入元素 - append()


np.array(arr, values, axis=None)

In [16]:
import numpy as np

In [17]:
a = np.arange(12)

In [18]:
np.append(a, [6, 4, 2])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  6,  4,  2])

In [19]:
b = np.reshape(a, (3, 4))

In [20]:
np.append(b, [1, 2, 3, 4])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2,  3,  4])

In [21]:
np.append(b, [[1, 2, 3, 4]], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]])

In [22]:
#np.append(b, [1, 2, 3, 4], axis=0) #error

In [23]:
c = np.linspace(0, 26, 12).reshape(3, 4)
c

array([[ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [24]:
d = np.append(b, c, axis=0)
d, d.shape

(array([[ 0.        ,  1.        ,  2.        ,  3.        ],
        [ 4.        ,  5.        ,  6.        ,  7.        ],
        [ 8.        ,  9.        , 10.        , 11.        ],
        [ 0.        ,  2.36363636,  4.72727273,  7.09090909],
        [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
        [18.90909091, 21.27272727, 23.63636364, 26.        ]]),
 (6, 4))

In [25]:
d = np.append(b, c, axis=1)
d, d.shape

(array([[ 0.        ,  1.        ,  2.        ,  3.        ,  0.        ,
          2.36363636,  4.72727273,  7.09090909],
        [ 4.        ,  5.        ,  6.        ,  7.        ,  9.45454545,
         11.81818182, 14.18181818, 16.54545455],
        [ 8.        ,  9.        , 10.        , 11.        , 18.90909091,
         21.27272727, 23.63636364, 26.        ]]),
 (3, 8))

# 判斷陣列真假值 - all() 與 any()


np.all(a, axis=None, out=None, keepdims=False)

np.all()會判斷ndarray裏的全部元素是否為True(不爲0)



In [26]:
import numpy as np

In [27]:
a = np.array([[1, 1, 1],
              [1, 0, 1],
              [1, 0, 1]])

In [28]:
np.all(a)

False

In [29]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.all(b)

True

In [31]:
np.all(a<2)

True

In [32]:
np.all(b%3<2)

True

In [33]:
np.all(a, axis=0)

array([ True, False,  True])

In [34]:
np.all(a, axis=1)

array([ True, False, False])

In [35]:
np.all(a, axis=0, keepdims=True)

array([[ True, False,  True]])

In [36]:
a.all(), b.all()

(False, True)

In [37]:
a.all(axis=1)

array([ True, False, False])

In [38]:
a<2, (a<2).all()

(array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]),
 True)

In [39]:
a.all(keepdims=True)

array([[False]])

np.any(a, axis=None, out=None, keepdims=False)

np.any()會判斷ndarray裏的至少一個元素是否為True(不爲0)


In [40]:
a = np.random.randint(10, size=(2, 3))
a

array([[8, 3, 6],
       [3, 5, 2]])

In [41]:
np.any(a==8)

True

In [42]:
np.any(a==9)

False

In [43]:
np.any(a%2==0,axis=0)

array([ True, False,  True])

In [44]:
np.any(a%2==1,axis=0)

array([ True,  True, False])

In [45]:
np.any(a%2==1,axis=0, keepdims=True)

array([[ True,  True, False]])

In [46]:
(a%5==0).any()

True

In [47]:
(a>3).any()

True

In [48]:
b = np.random.randint(10, size=(2, 3))
b

array([[4, 0, 4],
       [2, 9, 6]])

In [49]:
(a==b).any(axis=1)

array([False, False])

# 找出符合條件的元素 - where()

np.where(condition, x, y)

## 用法一：只指定條件式

In [50]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [51]:
np.where(a < 10)

(array([6, 7, 8, 9], dtype=int64),)

In [52]:
a[np.where(a < 10)]

array([8, 6, 4, 2])

In [53]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
np.where(a % 2 == 0)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 2, 0, 2, 0, 2], dtype=int64))

    i.e. a[0, 0]->0, a[0, 2]->2 ...

In [55]:
a[np.where(a % 2 == 0)]

array([ 0,  2,  4,  6,  8, 10])

## 用法二：在條件式後面加入x、y參數

In [56]:
np.where(a%2==0, 'even', 'odd')

array([['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd']], dtype='<U4')

In [57]:
#np.where(a%2==0, 'even') #error

In [58]:
b = np.reshape(a, (3, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
c = b ** 2
c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [60]:
np.where(b%2==0, b, c)

array([[  0,   1,   2,   9],
       [  4,  25,   6,  49],
       [  8,  81,  10, 121]])

# 取出最大值、最小值 - amax() 與 amin()

np.amax(a, axis=None, out=None, keepdims=False)

or

ndarray.max(axis=None, out=None, keepdims=False)

In [61]:
import numpy as np

In [62]:
np.amax(np.array([1, 2, 3, 2, 1]))

3

In [63]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [64]:
np.amax(a, axis=0)

array([3, 4])

In [65]:
np.amax(a, axis=1)

array([2, 4])

In [66]:
b = np.random.randint(30, size=(2, 3, 5))
b

array([[[17,  2, 16, 29, 22],
        [18,  3,  4, 11, 10],
        [ 0, 13, 29, 24, 16]],

       [[13, 23, 25, 18, 11],
        [27, 28, 20, 19,  5],
        [17,  0, 20, 29,  7]]])

In [67]:
b.max(axis=0)

array([[17, 23, 25, 29, 22],
       [27, 28, 20, 19, 10],
       [17, 13, 29, 29, 16]])

In [68]:
b.max(axis=1)

array([[18, 13, 29, 29, 22],
       [27, 28, 25, 29, 11]])

In [69]:
b.max(axis=2)

array([[29, 18, 29],
       [25, 28, 29]])

np.amin(a, axis=None, out=None, keepdims=False)

or

ndarray.min(axis=None, out=None, keepdims=False)

In [70]:
b = np.random.randint(30, size=(2, 3, 5))
b

array([[[28, 12, 26, 22,  0],
        [21,  1, 26, 19, 10],
        [14, 13, 28, 11, 10]],

       [[21, 22, 13, 19, 28],
        [15, 15, 19, 24, 13],
        [21, 25, 19,  3, 20]]])

In [71]:
np.amin(b, axis=0)

array([[21, 12, 13, 19,  0],
       [15,  1, 19, 19, 10],
       [14, 13, 19,  3, 10]])

In [72]:
np.amin(b, axis=1)

array([[14,  1, 26, 11,  0],
       [15, 15, 13,  3, 13]])

In [73]:
np.amin(b, axis=2)

array([[ 0,  1, 10],
       [13, 13,  3]])

# 取出最大值、最小值的索引位置 - argmax()、argmin()

np.argmax(a, axis=None, out=None)

In [74]:
import numpy as np

## 1D

In [75]:
a = np.random.randint(10, size=10)
a

array([7, 9, 9, 9, 3, 9, 2, 2, 0, 5])

In [76]:
np.argmax(a) #a[5]

1

In [77]:
a.argmax()

1

## 2D

In [78]:
b = np.random.randint(10, size=(3, 4))
b

array([[2, 9, 5, 1],
       [1, 8, 4, 8],
       [3, 3, 7, 5]])

自動將2D的陣列轉變成1D來運算

In [79]:
np.argmax(b)

1

In [80]:
np.argmax(b, axis=0)

array([2, 0, 2, 1], dtype=int64)

In [81]:
np.argmax(b, axis=1)

array([1, 1, 2], dtype=int64)

## 3D

In [82]:
c = np.random.randint(10, size=(2, 3, 4))
c

array([[[5, 4, 7, 0],
        [0, 6, 4, 7],
        [7, 3, 6, 9]],

       [[8, 3, 3, 1],
        [3, 7, 5, 2],
        [6, 8, 8, 6]]])

In [83]:
np.argmax(c, axis=0) # c[0, 0] > c[0, 1] ? 0 : 1

array([[1, 0, 0, 1],
       [1, 1, 1, 0],
       [0, 1, 1, 0]], dtype=int64)

In [84]:
np.argmax(c, axis=1)

array([[2, 1, 0, 2],
       [0, 2, 2, 2]], dtype=int64)

In [85]:
np.argmax(c, axis=2)

array([[2, 3, 3],
       [0, 1, 1]], dtype=int64)

np.argmin(a, axis=None, out=None)

In [86]:
d = np.random.randint(10, size=(3, 4))
d

array([[3, 5, 1, 1],
       [5, 7, 7, 8],
       [8, 3, 9, 8]])

In [87]:
np.argmin(d)

2

In [88]:
np.argmin(d, axis=0)

array([0, 2, 0, 0], dtype=int64)

In [89]:
np.argmin(d, axis=1)

array([2, 0, 1], dtype=int64)

In [90]:
d.argmin(axis=1)

array([2, 0, 1], dtype=int64)

# 陣列轉置 - transpose()

np.transpose(a, axes=None)

axes是axis的複數

axes=(1, 0, 2)是指將第0軸與第1軸對調

In [91]:
import numpy as np

In [92]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [94]:
np.transpose(a, (1, 0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [95]:
b = np.arange(6)
b, b.shape

(array([0, 1, 2, 3, 4, 5]), (6,))

In [96]:
np.transpose(b)

array([0, 1, 2, 3, 4, 5])

In [97]:
b = b.reshape(1, 6)
b, b.shape

(array([[0, 1, 2, 3, 4, 5]]), (1, 6))

In [98]:
b.transpose(), b.shape

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]),
 (1, 6))

In [99]:
c = np.arange(24).reshape(4, 3, 2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

沒有設定axes, 就代表自動代入(2, 1, 0)
i.e. (2, 7, 5) -> (5, 7, 2)

In [100]:
np.transpose(c), np.transpose(c).shape

(array([[[ 0,  6, 12, 18],
         [ 2,  8, 14, 20],
         [ 4, 10, 16, 22]],
 
        [[ 1,  7, 13, 19],
         [ 3,  9, 15, 21],
         [ 5, 11, 17, 23]]]),
 (2, 3, 4))

In [101]:
np.transpose(c, axes=(1, 0, 2)), np.transpose(c, axes=(1, 0, 2)).shape

(array([[[ 0,  1],
         [ 6,  7],
         [12, 13],
         [18, 19]],
 
        [[ 2,  3],
         [ 8,  9],
         [14, 15],
         [20, 21]],
 
        [[ 4,  5],
         [10, 11],
         [16, 17],
         [22, 23]]]),
 (3, 4, 2))

In [102]:
c.transpose(1, 0, 2)

array([[[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]],

       [[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]],

       [[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]]])

In [103]:
c.transpose(1, 0, 2).shape

(3, 4, 2)

ndarray.T 只能 (0, 1, 2) -> (2, 1, 0)

In [104]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [106]:
b

array([[0, 1, 2, 3, 4, 5]])

In [107]:
b.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [108]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [109]:
c.T

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

In [110]:
a.transpose().shape == a.T.shape

True

In [111]:
b.transpose().shape == b.T.shape

True

In [112]:
c.transpose().shape == c.T.shape

True

# 陣列排列 - sort() 與 argsort()

np.sort() vs np.argsort()

np.sort(a, axis=-1, kind='quicksort', order=None)：回傳值

np.argsort(a, axis=-1, kind='quicksort', order=None)：回傳索引值

kind: quicksort, mergesort, heapsort

In [113]:
import numpy as np

## 1D

In [114]:
a = np.random.randint(0, 100, size=20)
a

array([68, 93, 91, 32, 22,  2, 64, 18, 43, 15, 70, 22, 47, 62,  8, 47, 71,
       91, 48, 59])

In [115]:
np.sort(a)

array([ 2,  8, 15, 18, 22, 22, 32, 43, 47, 47, 48, 59, 62, 64, 68, 70, 71,
       91, 91, 93])

In [116]:
a = np.array([1, 3, 2])
np.argsort(a)

array([0, 2, 1], dtype=int64)

## 2D

In [117]:
b = np.random.randint(0, 100, size=20).reshape(4, 5)
b

array([[25, 11, 63, 61, 33],
       [12, 34, 97, 73, 59],
       [24, 23, 35, 48, 43],
       [79, 13, 11, 91, 52]])

In [118]:
np.sort(b)

array([[11, 25, 33, 61, 63],
       [12, 34, 59, 73, 97],
       [23, 24, 35, 43, 48],
       [11, 13, 52, 79, 91]])

In [119]:
np.argsort(b)

array([[1, 0, 4, 3, 2],
       [0, 1, 4, 3, 2],
       [1, 0, 2, 4, 3],
       [2, 1, 4, 0, 3]], dtype=int64)

In [120]:
np.sort(b, axis=0)

array([[12, 11, 11, 48, 33],
       [24, 13, 35, 61, 43],
       [25, 23, 63, 73, 52],
       [79, 34, 97, 91, 59]])

In [121]:
np.argsort(b, axis=0)

array([[1, 0, 3, 2, 0],
       [2, 3, 2, 0, 2],
       [0, 2, 0, 1, 3],
       [3, 1, 1, 3, 1]], dtype=int64)

## 3D

In [122]:
c = np.random.randint(0, 100, size=40).reshape(2, 4, 5)
c

array([[[ 0, 72,  2, 27, 88],
        [97, 29, 59, 88, 26],
        [75, 61, 66,  6, 79],
        [21, 31, 38, 75, 78]],

       [[43, 82, 54, 50, 92],
        [93, 82,  1, 12, 75],
        [79, 83, 24, 43, 65],
        [54, 70, 76, 14, 98]]])

In [123]:
np.sort(c)

array([[[ 0,  2, 27, 72, 88],
        [26, 29, 59, 88, 97],
        [ 6, 61, 66, 75, 79],
        [21, 31, 38, 75, 78]],

       [[43, 50, 54, 82, 92],
        [ 1, 12, 75, 82, 93],
        [24, 43, 65, 79, 83],
        [14, 54, 70, 76, 98]]])

In [124]:
np.sort(c, axis=0)

array([[[ 0, 72,  2, 27, 88],
        [93, 29,  1, 12, 26],
        [75, 61, 24,  6, 65],
        [21, 31, 38, 14, 78]],

       [[43, 82, 54, 50, 92],
        [97, 82, 59, 88, 75],
        [79, 83, 66, 43, 79],
        [54, 70, 76, 75, 98]]])

In [125]:
np.argsort(c, axis=0)

array([[[0, 0, 0, 0, 0],
        [1, 0, 1, 1, 0],
        [0, 0, 1, 0, 1],
        [0, 0, 0, 1, 0]],

       [[1, 1, 1, 1, 1],
        [0, 1, 0, 0, 1],
        [1, 1, 0, 1, 0],
        [1, 1, 1, 0, 1]]], dtype=int64)

## order用法

In [126]:
values = [('Catherine', 1, 8.6), ('Bob', 12, 7.6), ('Alice', 25, 9.6), 
          ('David', 10, 7.6)]
dt = [('name', 'S10'), ('ID', int), ('score', float)]

In [127]:
a = np.array(values, dtype=dt)

In [128]:
np.sort(a, order='name')

array([(b'Alice', 25, 9.6), (b'Bob', 12, 7.6), (b'Catherine',  1, 8.6),
       (b'David', 10, 7.6)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [129]:
np.sort(a, order='ID')

array([(b'Catherine',  1, 8.6), (b'David', 10, 7.6), (b'Bob', 12, 7.6),
       (b'Alice', 25, 9.6)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [130]:
np.sort(a, order='score')

array([(b'Bob', 12, 7.6), (b'David', 10, 7.6), (b'Catherine',  1, 8.6),
       (b'Alice', 25, 9.6)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [131]:
np.argsort(a, order='score')

array([1, 3, 0, 2], dtype=int64)

In [132]:
np.sort(a, order=['score', 'ID'])

array([(b'David', 10, 7.6), (b'Bob', 12, 7.6), (b'Catherine',  1, 8.6),
       (b'Alice', 25, 9.6)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [133]:
d = np.random.randint(0, 100, size=10)
d

array([84, 74,  7, 69, 21, 93, 91, 49, 49, 20])

In [134]:
np.sort(d)

array([ 7, 20, 21, 49, 49, 69, 74, 84, 91, 93])

    d并沒有改變

In [135]:
d

array([84, 74,  7, 69, 21, 93, 91, 49, 49, 20])

In [136]:
d.sort()
d

array([ 7, 20, 21, 49, 49, 69, 74, 84, 91, 93])

# 陣列合并 - hstack() 與 vstack()

np.hstack(tup)

hstack的字意就是沿著水平(horizontal)方向做合并、推叠，axis = 1

In [137]:
import numpy as np

## 1D

In [138]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [139]:
b = np.array([1, 2])

In [140]:
np.hstack((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2])

## 2D

In [141]:
c = np.arange(4).reshape(2, 2)
c

array([[0, 1],
       [2, 3]])

In [142]:
#np.hstack((c, a)) #error

In [143]:
d = np.arange(6).reshape(2, 3)
d

array([[0, 1, 2],
       [3, 4, 5]])

In [144]:
np.hstack((c, d))

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5]])

In [145]:
e = np.arange(12).reshape(2, 2, 3)
e, e.shape

(array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]]]),
 (2, 2, 3))

In [146]:
f = np.arange(6).reshape(2, 1, 3)
f, f.shape

(array([[[0, 1, 2]],
 
        [[3, 4, 5]]]),
 (2, 1, 3))

In [147]:
np.hstack((e, f)), np.hstack((e, f)).shape

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 0,  1,  2]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11],
         [ 3,  4,  5]]]),
 (2, 3, 3))

               可合并                             不可合并
    
          (2, 3) 與 (2, 4)                    (2, 3) 與 (4, 2)
    
          (2, 2) 與 (2, 2)                    (2, 2) 與 (3, 2)
    
       (1, 2, 3) 與 (1, 4, 3)              (1, 2, 3) 與 (2, 2, 3)
    
    (2, 5, 3, 2) 與 (2, 9, 3, 2)        (2, 5, 3, 2) 與 (2, 5, 9, 2)

np.vstack(tup)

vstack的字意就是沿著垂直(vertical)方向做合并、推叠，axis = 0

## 1D

In [148]:
a = np.arange(12).reshape(-1, 1)
a## 2D

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [149]:
b = np.arange(2).reshape(-1, 1)
b

array([[0],
       [1]])

In [150]:
np.vstack((a, b))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [ 0],
       [ 1]])

In [151]:
c = np.arange(2).reshape(1, 2)
c

array([[0, 1]])

In [152]:
#np.vstack((a, c)) #error

## 2D

In [153]:
d = np.arange(4).reshape(2, 2)
d## 2D

array([[0, 1],
       [2, 3]])

In [154]:
np.vstack((c, d))    

array([[0, 1],
       [0, 1],
       [2, 3]])

## 2D

In [155]:
e = np.arange(24).reshape(4, 3, 2)
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [156]:
f = np.arange(6).reshape(1, 3, 2)
f

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [157]:
np.vstack((e, f)), np.vstack((e, f)).shape

(array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]],
 
        [[12, 13],
         [14, 15],
         [16, 17]],
 
        [[18, 19],
         [20, 21],
         [22, 23]],
 
        [[ 0,  1],
         [ 2,  3],
         [ 4,  5]]]),
 (5, 3, 2))

               可合并                             不可合并
    
          (2, 3) 與 (3, 3)                    (2, 3) 與 (2, 2)
    
          (2, 2) 與 (2, 2)                    (2, 2) 與 (2, 5)
    
       (1, 2, 3) 與 (4, 2, 3)              (1, 2, 3) 與 (1, 2, 2)
    
    (2, 5, 3, 2) 與 (9, 5, 3, 2)        (2, 5, 3, 2) 與 (2, 7, 3, 2)