# 建立都是0的陣列 - zeros()

np.zeros(shape, dtype=float, order='C')

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
a = np.zeros((3, 4))
a, a.shape

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 (3, 4))

In [5]:
np.zeros_like(a.shape)

array([0, 0])

In [6]:
np.zeros_like(a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 建立都是1的陣列 - ones()

np.ones(shape, dtype=float, order='C')

In [7]:
import numpy as np

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones(4, dtype=np.int8)

array([1, 1, 1, 1], dtype=int8)

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
b = np.array([1, 2, 3], dtype=np.int8)
b

array([1, 2, 3], dtype=int8)

In [14]:
np.ones_like(b)

array([1, 1, 1], dtype=int8)

# 建立「不限定元素值」的陣列 - empty()

np.empty(shape, dtype=float, order='C')

In [15]:
import numpy as np

In [16]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.empty((3, 3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.54932307e-321],
       [6.23040373e-307, 2.22520627e-307, 6.23048861e-307]])

In [18]:
#%timeit np.zeros(10000)

In [19]:
#%timeit np.ones(10000)

In [20]:
#%timeit np.empty(10000)

以上可見 np.empty()在建立陣列的速度快很多

# 建立指定範圍的等差陣列 - arange()

np.arange(start, stop, step, dtype=None)

In [21]:
import numpy as np

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(-10)

array([], dtype=int32)

In [24]:
np.arange(4.5)

array([0., 1., 2., 3., 4.])

In [25]:
np.arange(1, 8)

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0.5, 5.5)

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [28]:
np.arange(0.55, 5.55)

array([0.55, 1.55, 2.55, 3.55, 4.55])

In [29]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [30]:
np.arange(2, 5, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8])

In [31]:
np.arange(5, 2, -1)

array([5, 4, 3])

In [32]:
#np.arange(stop=5, step=2) #error

In [33]:
np.arange(5, dtype=np.float64)

array([0., 1., 2., 3., 4.])

In [34]:
np.arange(5.0, dtype=int)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(0, 5, 0.5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.arange(0, 5, 1.5, dtype=int)

array([0, 1, 2, 3])

# 建立指定範圍的等差陣列 - linspace()

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=float)

num:切割後陣列裏的元素數量

endpoint:建立的陣列是否包含stop

retstep:是否顯示元素之間的遞增量

遞增量 = (stop - start) / (num - 1)

In [37]:
import numpy as np

In [38]:
np.linspace(0 ,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [39]:
np.linspace(0 ,1).size

50

    遞增量 = (49 - 0) / (50 - 1) = 1

In [40]:
np.linspace(0 ,49)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [41]:
np.linspace(0 ,2, num=3, retstep=True)

(array([0., 1., 2.]), 1.0)

In [42]:
np.linspace(0 ,2, num=3, retstep=False)

array([0., 1., 2.])

# 建立單位矩陣 - eye() 與 identity()

np.eye(N, M=None, k=0, dtype=float, order='C')

In [43]:
import numpy as np

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [46]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [47]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [48]:
np.eye(5, k=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [52]:
np.eye(5, k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

np.identity(N, dtype=float) #很少用#

In [53]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
#%timeit np.eye(10000)

In [55]:
#%timeit np.identity(10000)

以上顯示 時間差不多 可是np.eye()功能比np.identity() 所以通常只會用np.eye（）

# 將矩陣展平為1D - flatten()

ndarray.flatten(order='C')

回傳copy的 比ravel()慢

In [56]:
import numpy as np

In [57]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
b = a.flatten()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a.shape, b.shape

((2, 5), (10,))

In [60]:
c = np.arange(12).reshape(2, 2, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [61]:
d = c.flatten()
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
c.shape, d.shape

((2, 2, 3), (12,))

# 將矩陣展平為1D - ravel()

np.ravel(a, order='C')

ndarray.ravel(order='C')

回傳reference的 比flatten()快

In [63]:
import numpy as np

In [64]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a.ravel(order='C')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a.ravel(order='F')

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [69]:
b = a.ravel()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
b += 1
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
c = np.arange(10).reshape(2, 5, order='F')
c

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [72]:
c.ravel(order='F')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
c.ravel(order='A') # follow its style

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
c.ravel(order='C')

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

# 找出不是0的元素 - nonzero()

np.nonzero(a)

ndarray.nonzero()

almost like np.where(a!=0)

In [75]:
import numpy as np

In [76]:
np.random.seed(49999)
a = np.random.randint(10, size=20)
a

array([7, 4, 3, 7, 0, 4, 6, 0, 7, 2, 3, 8, 1, 0, 0, 9, 2, 8, 1, 9])

In [77]:
a.nonzero()

(array([ 0,  1,  2,  3,  5,  6,  8,  9, 10, 11, 12, 15, 16, 17, 18, 19],
       dtype=int64),)

In [78]:
np.nonzero(a)

(array([ 0,  1,  2,  3,  5,  6,  8,  9, 10, 11, 12, 15, 16, 17, 18, 19],
       dtype=int64),)

In [79]:
a[np.nonzero(a)]

array([7, 4, 3, 7, 4, 6, 7, 2, 3, 8, 1, 9, 2, 8, 1, 9])

In [80]:
np.random.seed(49999)
b = np.random.randint(0, 10, size=(4,5))
b

array([[7, 4, 3, 7, 0],
       [4, 6, 0, 7, 2],
       [3, 8, 1, 0, 0],
       [9, 2, 8, 1, 9]])

In [81]:
b.nonzero() #2d index

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 3, 4, 0, 1, 2, 0, 1, 2, 3, 4], dtype=int64))

In [82]:
b[b.nonzero()]

array([7, 4, 3, 7, 4, 6, 7, 2, 3, 8, 1, 9, 2, 8, 1, 9])

# 複製陣列元素, 拼凑成新陣列 - tile()

np.tile(a, reps)

In [83]:
import numpy as np

In [84]:
a = np.array([0, 1, 2])

In [85]:
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [86]:
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [87]:
np.tile(a, (2, 3, 4))

array([[[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]]])

# 增加陣列的軸數 - np.newaxis

ndarray[:, np.newaxis] or ndarray[:,None]

In [88]:
import numpy as np

In [89]:
np.newaxis is None

True

In [90]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
x[np.newaxis, :, :], x[np.newaxis, :].shape

(array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]]),
 (1, 3, 5))

In [92]:
x[:, np.newaxis, :], x[:, np.newaxis, :].shape

(array([[[ 0,  1,  2,  3,  4]],
 
        [[ 5,  6,  7,  8,  9]],
 
        [[10, 11, 12, 13, 14]]]),
 (3, 1, 5))

In [93]:
x[:, None, :], x[:, None, :].shape

(array([[[ 0,  1,  2,  3,  4]],
 
        [[ 5,  6,  7,  8,  9]],
 
        [[10, 11, 12, 13, 14]]]),
 (3, 1, 5))

In [94]:
x = x.flatten()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [95]:
x[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [96]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [97]:
np.reshape(x, (1, 3, 5)) #same as x[np.newaxis, :, :]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [98]:
np.reshape(x, (3, 1, 5)) #same as x[:, np.newaxis, :]

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

In [99]:
x = x.flatten()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [100]:
np.reshape(x, (-1, 1)) #same as x[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

reshape() 缺點：無法在不確定維度的情況下增加軸數

# 陣列合并 - np.r_ 與 np.c_ 物件

np.r_ 與 np.c_ 同樣具有合并陣列的用途(like np.hstack(), np.vstack())

不過他們的功能不僅用於合并，還可像np.arange()一樣切片來建立陣列

用法一：合并陣列(不設定控制字串)

np.r_[] 可以想象成 np.vstack(), axis = 0, row

In [101]:
import numpy as np

In [102]:
a = np.array([1, 2, 3])
b = np.array([4, 5 ,6])

In [103]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [104]:
np.r_[2, 3, 5, np.array([1, 2]), 4.2]

array([2. , 3. , 5. , 1. , 2. , 4.2])

In [105]:
c = np.zeros((2, 3))
d = np.ones((3, 3))

In [106]:
np.r_[c, d]

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [107]:
d = np.ones((3, 4))

In [108]:
#np.r_[c, d] #error

用法二：合并陣列(設定控制字串)

np.r_['x, y, z',陣列或數值, ...]

x:設定合并哪一軸的元素

y:設定合并後的陣列至少為幾軸

z:依y的設定，原始陣列可能需要增加軸數，z則指定了增軸的方式

In [109]:
a = np.ones((2, 2))
b = np.zeros((2, 2))

In [110]:
np.r_['0', a, b], np.r_['0', a, b].shape 
#same as np.r_[a, b], np.r_[a, b].shape

(array([[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]]),
 (4, 2))

In [111]:
np.r_['1', a, b], np.r_['1', a, b].shape

(array([[1., 1., 0., 0.],
        [1., 1., 0., 0.]]),
 (2, 4))

In [112]:
c = np.ones((2, 2, 2))
c

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [113]:
d = np.zeros((2, 2, 2))
d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [114]:
np.r_['0', c, d], np.r_['0', c, d].shape

(array([[[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]],
 
        [[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]]]),
 (4, 2, 2))

In [115]:
np.r_['1', c, d], np.r_['1', c, d].shape

(array([[[1., 1.],
         [1., 1.],
         [0., 0.],
         [0., 0.]],
 
        [[1., 1.],
         [1., 1.],
         [0., 0.],
         [0., 0.]]]),
 (2, 4, 2))

In [116]:
np.r_['2', c, d], np.r_['2', c, d].shape

(array([[[1., 1., 0., 0.],
         [1., 1., 0., 0.]],
 
        [[1., 1., 0., 0.],
         [1., 1., 0., 0.]]]),
 (2, 2, 4))

    假設x.shape=(3,), [x, y z] = ['0','2','1']
    y = '2' -> 變2D ->x.shape = ( ,3)
    z = '1' -> 把該軸設定爲z軸 -> x.shape = (1,3)
    ps:z default 是 -1 也就是最後一個軸

In [117]:
np.r_['0, 2', [0, 1, 2], [3, 3, 3]]

array([[0, 1, 2],
       [3, 3, 3]])

In [118]:
np.r_['0, 2', [0, 1, 2], [3, 3, 3]].shape

(2, 3)

In [119]:
np.r_['0, 3', [0, 1, 2], [3, 3, 3]]

array([[[0, 1, 2]],

       [[3, 3, 3]]])

In [120]:
np.r_['0, 3', [0, 1, 2], [3, 3, 3]].shape

(2, 1, 3)

In [121]:
np.r_['0, 3, -1', [0, 1, 2], [3, 3, 3]]

array([[[0, 1, 2]],

       [[3, 3, 3]]])

In [122]:
np.r_['0, 3, 0', [0, 1, 2], [3, 3, 3]]

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[3]],

       [[3]]])

In [123]:
np.r_['0, 3, 0', [0, 1, 2], [3, 3, 3]].shape

(6, 1, 1)

用法三：用切片語法建立陣列

np.r_[start:stop:step,1D陣列或數值, ...]

In [124]:
np.r_[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
np.r_[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.r_[0:10:2]

array([0, 2, 4, 6, 8])

In [127]:
np.r_[10:0:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [128]:
np.r_[0:10, 0, 4, np.array([3, 3])]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 4, 3, 3])

用法四：傳入‘r’,‘c’字串建立矩陣物件

np.r_['r'or'c',陣列或數值, ...]

In [129]:
a = np.array([1, 4, 6])
b = np.array([2, 2, 2])

In [130]:
np.r_['r',a, b]

matrix([[1, 4, 6, 2, 2, 2]])

In [131]:
np.r_['c',a, b]

matrix([[1],
        [4],
        [6],
        [2],
        [2],
        [2]])

In [132]:
c = np.ones((4, 5))
d = np.zeros((2, 5))

In [133]:
np.r_['r', c, d]

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [134]:
np.r_['c', c, d]

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

由於np.r_預設合并第0軸 因此上面的都一樣

其實np.r_熟練也是可以達到np.c_的效果

尤其合并np.c_ 使用兩種反而會搞混

np.c_[a, b] = np.r_['-1, 2, 0', a, b]

In [135]:
a = np.ones((3, 2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [136]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [137]:
np.c_[a, b]

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [138]:
c = np.array([0., 0., 0.])
c

array([0., 0., 0.])

In [139]:
np.c_[a, c]

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

In [140]:
np.c_[a, c].shape

(3, 3)

# 陣列的儲存與讀取 - save() 與 load()

np.save(file, arr, allow_pickle=True, fix_imports=True)

np.load(file, mmap_mode=None, allow_pickle=True, fix_imports=True, encoding='ASCII)

file type : .npy, binary

In [141]:
import numpy as np

In [142]:
a = np.random.rand(1200*1000).reshape(1200, -1)
a

array([[0.68564811, 0.59074925, 0.52409275, ..., 0.21237303, 0.13779091,
        0.8702217 ],
       [0.13718706, 0.9692734 , 0.57066862, ..., 0.39969501, 0.15393687,
        0.4939711 ],
       [0.93890797, 0.85526525, 0.17935707, ..., 0.29193435, 0.74422616,
        0.89675888],
       ...,
       [0.82105537, 0.35343753, 0.15240969, ..., 0.8872634 , 0.58645936,
        0.59859669],
       [0.12249704, 0.34544702, 0.37673506, ..., 0.92308593, 0.98092524,
        0.09030762],
       [0.05224381, 0.4920884 , 0.42878644, ..., 0.04548954, 0.7770869 ,
        0.17348117]])

In [143]:
np.save('source/a', a)

In [144]:
b = np.load('source/a.npy')
b

array([[0.68564811, 0.59074925, 0.52409275, ..., 0.21237303, 0.13779091,
        0.8702217 ],
       [0.13718706, 0.9692734 , 0.57066862, ..., 0.39969501, 0.15393687,
        0.4939711 ],
       [0.93890797, 0.85526525, 0.17935707, ..., 0.29193435, 0.74422616,
        0.89675888],
       ...,
       [0.82105537, 0.35343753, 0.15240969, ..., 0.8872634 , 0.58645936,
        0.59859669],
       [0.12249704, 0.34544702, 0.37673506, ..., 0.92308593, 0.98092524,
        0.09030762],
       [0.05224381, 0.4920884 , 0.42878644, ..., 0.04548954, 0.7770869 ,
        0.17348117]])

In [145]:
b.shape

(1200, 1000)

以上缺點:無法兼容于python以外的程式語言或軟體工具

# 以文字格式儲存與讀取陣列 - savetxt() 與 loadtxt()

缺點：最高只能儲存2D的陣列

np.savetxt(fname, X, fmt, delimiter, newline, header, footer, comments, encoding)

np.loadtxt(fname, dtype, comment, delimiter, converters, skiprows, usecols, unpack, ndim, encoding)

In [146]:
import numpy as np

In [147]:
a = np.random.rand(3, 4)
a

array([[0.38251563, 0.87639315, 0.29097544, 0.46843954],
       [0.61090723, 0.25777427, 0.73009274, 0.01220844],
       [0.66506052, 0.93097831, 0.63279316, 0.83611651]])

In [148]:
np.savetxt('source/sample1.txt', a)

In [149]:
b = np.loadtxt('source/sample1.txt')
b

array([[0.38251563, 0.87639315, 0.29097544, 0.46843954],
       [0.61090723, 0.25777427, 0.73009274, 0.01220844],
       [0.66506052, 0.93097831, 0.63279316, 0.83611651]])

In [150]:
np.savetxt('source/sample1.csv', a)

In [151]:
c = np.loadtxt('source/sample1.csv')
c

array([[0.38251563, 0.87639315, 0.29097544, 0.46843954],
       [0.61090723, 0.25777427, 0.73009274, 0.01220844],
       [0.66506052, 0.93097831, 0.63279316, 0.83611651]])

In [152]:
np.savetxt('source/sample2.txt', a, delimiter=',') #請查看sample2.txt

In [153]:
#c = np.loadtxt('source/sample2.txt') #error

In [154]:
c = np.loadtxt('source/sample2.txt', delimiter=',')
c

array([[0.38251563, 0.87639315, 0.29097544, 0.46843954],
       [0.61090723, 0.25777427, 0.73009274, 0.01220844],
       [0.66506052, 0.93097831, 0.63279316, 0.83611651]])

In [155]:
np.savetxt('source/sample3.txt', a, fmt='%.2e') #請查看sample3.txt

In [156]:
np.savetxt('source/sample4.txt', a, fmt='%.2f') #請查看sample4.txt

In [157]:
np.savetxt('source/sample5.txt', a, fmt='%.3e',
          header='this is a header', footer='this is a footer') 
#請查看sample5.txt

In [158]:
np.savetxt('source/sample6.txt', a, fmt='%.3e',header='this is a header', 
           footer='this is a footer', comments='>>>') 
#請查看sample6.txt

In [159]:
np.loadtxt('source/sample4.txt')

array([[0.38, 0.88, 0.29, 0.47],
       [0.61, 0.26, 0.73, 0.01],
       [0.67, 0.93, 0.63, 0.84]])

In [160]:
np.loadtxt('source/sample4.txt', usecols=(0,2))

array([[0.38, 0.29],
       [0.61, 0.73],
       [0.67, 0.63]])

In [161]:
np.loadtxt('source/sample4.txt', skiprows=1) #skiprows=開頭前幾行

array([[0.61, 0.26, 0.73, 0.01],
       [0.67, 0.93, 0.63, 0.84]])

In [162]:
np.loadtxt('foo.csv', dtype=[('col1', 'i8'),
                             ('col2', 'S10'),
                             ('col3', 'f8'),
                             ('col4', 'S10')
                            ])

array([(18, b'female', 154.1, b'No'), (21, b'male', 172.3, b'Yes'),
       (22, b'female', 160.8, b'Yes'), (23, b'male', 190.1, b'Yes'),
       (25, b'female', 156. , b'No')],
      dtype=[('col1', '<i8'), ('col2', 'S10'), ('col3', '<f8'), ('col4', 'S10')])

In [163]:
np.loadtxt('foo.csv', dtype=[('col1', 'i8'),
                             ('col2', 'S10'),
                             ('col3', 'f8'),
                             ('col4', 'S10')
                            ], unpack=True)

[array([18, 21, 22, 23, 25], dtype=int64),
 array([b'female', b'male', b'female', b'male', b'female'], dtype='|S10'),
 array([154.1, 172.3, 160.8, 190.1, 156. ]),
 array([b'No', b'Yes', b'Yes', b'Yes', b'No'], dtype='|S10')]

In [164]:
age,gender,tall,driver_license=np.loadtxt('foo.csv', dtype=[('col1', 'i8'),
                                                                 ('col2', 'S10'),
                                                                 ('col3', 'f8'),
                                                                 ('col4', 'S10')
                                                                ], unpack=True)

In [165]:
age

array([18, 21, 22, 23, 25], dtype=int64)

In [166]:
gender

array([b'female', b'male', b'female', b'male', b'female'], dtype='|S10')

In [167]:
tall

array([154.1, 172.3, 160.8, 190.1, 156. ])

In [168]:
driver_license

array([b'No', b'Yes', b'Yes', b'Yes', b'No'], dtype='|S10')

In [169]:
def driver_license(str):
    if str == b'Yes':
        return 1
    else:
        return -1

In [170]:
def gender(str):
    if str == b'male':
        return 1
    else:
        return -1

In [171]:
np.loadtxt('foo.csv', converters={1:gender, 3:driver_license})

array([[ 18. ,  -1. , 154.1,  -1. ],
       [ 21. ,   1. , 172.3,   1. ],
       [ 22. ,  -1. , 160.8,   1. ],
       [ 23. ,   1. , 190.1,   1. ],
       [ 25. ,  -1. , 156. ,  -1. ]])

# 建立隨機亂數的陣列 - random()

np.random.rand(d0, d1, ...dn)

np.random.randint(low, high, size, dtype)

In [172]:
import numpy as np

In [173]:
np.random.rand()

0.27534036869868517

In [174]:
np.random.randint(10)

2

In [175]:
np.random.rand(2, 3)

array([[0.81681384, 0.26096324, 0.46271943],
       [0.2940405 , 0.19868471, 0.85686904]])

In [176]:
np.random.randint(10, size=(2, 3))

array([[6, 9, 7],
       [7, 5, 4]])

In [177]:
np.random.randint(5, 10, size=10)

array([6, 8, 5, 6, 8, 5, 7, 7, 8, 9])

In [178]:
#(stop - start) * np.random.rand() + start 回歸分析
(10 - 5) * np.random.rand(10) + 5

array([9.09680191, 6.646596  , 9.58068133, 9.44748915, 9.82959767,
       8.69775166, 6.92476023, 8.46621515, 5.94590758, 6.76523058])

np.random.seed(seed)

np.random模組的亂數產生器在初始化時，會使用一個整數來作爲seed

seed不變 random出來的結果就不變

In [179]:
np.random.seed(20)

In [180]:
np.random.rand()

0.5881308010772742

In [181]:
np.random.seed(20)
np.random.rand()

0.5881308010772742

np.random.choice(a, size, replace=True, p)

np.random.choice不僅可以隨機取出元素， 還可用replace來控制是否取出重複的元素

In [182]:
a = ['Python', 'Ruby', 'Java', 'C++', 'PHP']

In [183]:
np.random.seed(4002)
np.random.choice(a, 3)

array(['Java', 'Python', 'Java'], dtype='<U6')

In [184]:
np.random.seed(4002)
np.random.choice(a, 3, replace=False)

array(['PHP', 'C++', 'Ruby'], dtype='<U6')

In [185]:
np.random.seed(4002)
np.random.choice(a, 20, p=[0.75, 0.05, 0.05, 0.05, 0.1]) #各個元素的權重
# p的總和 = 1

array(['Python', 'Java', 'C++', 'Python', 'Python', 'Python', 'Python',
       'Python', 'Python', 'Python', 'Java', 'PHP', 'Python', 'Java',
       'Python', 'Python', 'Python', 'Python', 'Python', 'Python'],
      dtype='<U6')

In [186]:
np.random.seed(4002)
np.random.choice(5, 10)
# 0 ~ 5

array([2, 0, 2, 3, 0, 1, 1, 2, 1, 3])

np.random.shuffle(a)

In [187]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
np.random.shuffle(a)
a

array([9, 1, 4, 7, 2, 3, 0, 6, 5, 8])