# 取出最大值、最小值 - amax() 與 amin()

## np.amax()

    np.amax(a, axis=None, out=None, keepdims=False)
    ndarray.max(axis=None, out=None, keepdims=False)

In [1]:
import numpy as np

In [2]:
np.amax(np.array([1, 2, 3, 2, 1]))

3

In [3]:
a = np.arange(1, 5).reshape(2, 2)
a

array([[1, 2],
       [3, 4]])

In [4]:
np.amax(a, axis=0)

array([3, 4])

In [5]:
np.amax(a, axis=1)

array([2, 4])

In [6]:
np.amax(a, axis=1)

array([2, 4])

In [7]:
b = np.random.randint(30, size=(2, 3, 5))
b

array([[[ 1,  8, 22, 10, 18],
        [25, 10, 21,  5,  3],
        [27, 26, 13, 13, 11]],

       [[ 4, 28, 28,  7,  0],
        [14, 11, 16, 15, 22],
        [ 5,  7,  9, 20, 19]]])

In [8]:
b.max(axis=0)

array([[ 4, 28, 28, 10, 18],
       [25, 11, 21, 15, 22],
       [27, 26, 13, 20, 19]])

In [9]:
b.max(axis=1)

array([[27, 26, 22, 13, 18],
       [14, 28, 28, 20, 22]])

In [10]:
b.max(axis=2)

array([[22, 25, 27],
       [28, 22, 20]])

## np.amax()

    np.amin(a, axis=None, out=None, keepdims=False)
    ndarray.min(axis=None, out=None, keepdims=False)

In [11]:
b = np.random.randint(30, size=(2, 3, 5))
b

array([[[17, 19, 27, 26,  4],
        [ 8, 18, 22, 29,  9],
        [20, 24, 17, 18, 20]],

       [[28,  6, 13, 10, 29],
        [15, 23,  2,  4, 18],
        [ 2, 22, 27, 23, 22]]])

In [12]:
np.amin(b, axis=0)

array([[17,  6, 13, 10,  4],
       [ 8, 18,  2,  4,  9],
       [ 2, 22, 17, 18, 20]])

In [13]:
np.amin(b, axis=1)

array([[ 8, 18, 17, 18,  4],
       [ 2,  6,  2,  4, 18]])

In [14]:
np.amin(b, axis=2)

array([[ 4,  8, 17],
       [ 6,  2,  2]])