# 判斷陣列真假值 - all() 與 any()

## np.all()

    np.all(a, axis=None, out=None, keepdims=False)
    np.all()會判斷ndarray裏的全部元素是否為True(不爲0)

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 1, 1],
              [1, 0, 1],
              [1, 0, 1]])

In [3]:
np.all(a)

False

In [4]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.all(b)

True

In [6]:
np.all(a<2)

True

In [7]:
np.all(b%3<2)

True

In [8]:
np.all(a, axis=0)

array([ True, False,  True])

In [9]:
np.all(a, axis=1)

array([ True, False, False])

In [10]:
np.all(a, axis=0, keepdims=True)

array([[ True, False,  True]])

In [11]:
a.all(), b.all()

(False, True)

In [12]:
a.all(axis=1)

array([ True, False, False])

In [13]:
a<2, (a<2).all()

(array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]),
 True)

In [14]:
a.all(keepdims=True)

array([[False]])

In [15]:
a.all(keepdims=True)

array([[False]])

## np.any

    np.any(a, axis=None, out=None, keepdims=False)
    np.any()會判斷ndarray裏的至少一個元素是否為True(不爲0)


In [16]:
a = np.random.randint(10, size=(2, 3))
a

array([[4, 8, 6],
       [9, 7, 5]])

In [17]:
np.any(a==8)

True

In [18]:
np.any(a==9)

True

In [19]:
np.any(a%2==0,axis=0)

array([ True,  True,  True])

In [20]:
np.any(a%2==1,axis=0)

array([ True,  True,  True])

In [21]:
np.any(a%2==1,axis=0, keepdims=True)

array([[ True,  True,  True]])

In [22]:
(a%5==0).any()

True

In [23]:
(a>3).any()

True

In [24]:
b = np.random.randint(10, size=(2, 3))
b

array([[4, 4, 7],
       [1, 9, 1]])

In [25]:
(a==b).any(axis=1)

array([ True, False])