## 在陣列最後面加入元素 - append()

    np.array(arr, values, axis=None)

In [1]:
import numpy as np

In [2]:
a = np.arange(12)

In [3]:
np.append(a, [6, 4, 2])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  6,  4,  2])

In [4]:
b = np.reshape(a, (3, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
np.append(b, [1, 2, 3, 4]) # 如沒有指定axis 會變成1D然後進行append

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2,  3,  4])

In [6]:
np.append(b, [[1, 2, 3, 4]], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]])

In [7]:
#np.append(b, [1, 2, 3, 4], axis=0) #error

In [8]:
c = np.linspace(0, 26, 12).reshape(3, 4)
c

array([[ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [9]:
d = np.append(b, c, axis=0)
d, d.shape

(array([[ 0.        ,  1.        ,  2.        ,  3.        ],
        [ 4.        ,  5.        ,  6.        ,  7.        ],
        [ 8.        ,  9.        , 10.        , 11.        ],
        [ 0.        ,  2.36363636,  4.72727273,  7.09090909],
        [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
        [18.90909091, 21.27272727, 23.63636364, 26.        ]]),
 (6, 4))

In [10]:
d = np.append(b, c, axis=1)
d, d.shape

(array([[ 0.        ,  1.        ,  2.        ,  3.        ,  0.        ,
          2.36363636,  4.72727273,  7.09090909],
        [ 4.        ,  5.        ,  6.        ,  7.        ,  9.45454545,
         11.81818182, 14.18181818, 16.54545455],
        [ 8.        ,  9.        , 10.        , 11.        , 18.90909091,
         21.27272727, 23.63636364, 26.        ]]),
 (3, 8))