# 建立指定範圍的等差陣列 - arange()

    np.arange(start, stop, step, dtype=None)

In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(-10)

array([], dtype=int32)

In [4]:
np.arange(4.5)

array([0., 1., 2., 3., 4.])

In [5]:
np.arange(1, 8)

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0.5, 5.5)

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [8]:
np.arange(0.55, 5.55)

array([0.55, 1.55, 2.55, 3.55, 4.55])

In [9]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [10]:
np.arange(2, 5, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8])

In [11]:
np.arange(5, 2, -1)

array([5, 4, 3])

In [12]:
#np.arange(stop=5, step=2) #error

In [13]:
np.arange(5, dtype=np.float64)

array([0., 1., 2., 3., 4.])

In [14]:
np.arange(5.0, dtype=int)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(0, 5, 0.5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.arange(0, 5, 1.5, dtype=int)

array([0, 1, 2, 3])