# 取出最大值、最小值的索引位置 - argmax()、argmin()

## np.argmax()

    np.argmax(a, axis=None, out=None)

In [1]:
import numpy as np

### 1D

In [2]:
a = np.random.randint(10, size=10)
a

array([7, 1, 8, 3, 8, 1, 1, 7, 6, 8])

In [3]:
np.argmax(a) # its index

2

In [4]:
a.argmax()

2

### 2D

In [5]:
b = np.random.randint(10, size=(3, 4))
b

array([[9, 7, 5, 0],
       [2, 7, 2, 5],
       [9, 2, 9, 7]])

In [6]:
np.argmax(b)

0

In [7]:
np.argmax(b, axis=0)

array([0, 0, 2, 2], dtype=int64)

In [8]:
np.argmax(b, axis=1)

array([0, 1, 0], dtype=int64)

### 3D

In [9]:
c = np.random.randint(10, size=(2, 3, 4))
c

array([[[0, 5, 8, 6],
        [7, 5, 1, 5],
        [8, 8, 3, 2]],

       [[2, 1, 8, 3],
        [8, 2, 5, 7],
        [8, 8, 0, 1]]])

In [10]:
np.argmax(c, axis=0) # c[0, 0] > c[0, 1] ? 0 : 1 .....

array([[1, 0, 0, 0],
       [1, 0, 1, 1],
       [0, 0, 0, 0]], dtype=int64)

In [11]:
np.argmax(c, axis=1)

array([[2, 2, 0, 0],
       [1, 2, 0, 1]], dtype=int64)

In [12]:
np.argmax(c, axis=2)

array([[2, 0, 0],
       [2, 0, 0]], dtype=int64)

## np.argmin()

    np.argmin(a, axis=None, out=None)

In [13]:
d = np.random.randint(10, size=(3, 4))
d

array([[9, 8, 2, 1],
       [0, 2, 0, 2],
       [5, 5, 4, 1]])

In [14]:
np.argmin(d)

4

In [15]:
np.argmin(d, axis=0)

array([1, 1, 1, 0], dtype=int64)

In [16]:
np.argmin(d, axis=1)

array([3, 0, 3], dtype=int64)

In [17]:
d.argmin(axis=1)

array([3, 0, 3], dtype=int64)