# 陣列合并 - hstack() 與 vstack()

## np.hstack()

    np.hstack(tup)
    hstack的字意就是沿著水平(horizontal)方向做合并、推叠，axis = 1

In [1]:
import numpy as np

### 1D

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
b = np.array([1, 2])

In [4]:
np.hstack((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  2])

### 2D

In [5]:
c = np.arange(4).reshape(2, 2)
c

array([[0, 1],
       [2, 3]])

In [6]:
#np.hstack((c, a)) #error

In [7]:
d = np.arange(6).reshape(2, 3)
d

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
np.hstack((c, d))

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5]])

### 3D

In [9]:
e = np.arange(12).reshape(2, 2, 3)
e, e.shape

(array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]]]),
 (2, 2, 3))

In [10]:
f = np.arange(6).reshape(2, 1, 3)
f, f.shape

(array([[[0, 1, 2]],
 
        [[3, 4, 5]]]),
 (2, 1, 3))

In [11]:
np.hstack((e, f)), np.hstack((e, f)).shape

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 0,  1,  2]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11],
         [ 3,  4,  5]]]),
 (2, 3, 3))

               可合并                             不可合并
    
          (2, 3) 與 (2, 4)                    (2, 3) 與 (4, 2)
    
          (2, 2) 與 (2, 2)                    (2, 2) 與 (3, 2)
    
       (1, 2, 3) 與 (1, 4, 3)              (1, 2, 3) 與 (2, 2, 3)
    
    (2, 5, 3, 2) 與 (2, 9, 3, 2)        (2, 5, 3, 2) 與 (2, 5, 9, 2)

## np.vstack()

    np.vstack(tup)
    vstack的字意就是沿著垂直(vertical)方向做合并、推叠，axis = 0

### 1D

In [12]:
a = np.arange(12).reshape(-1, 1)
a## 2D

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [13]:
b = np.arange(2).reshape(-1, 1)
b

array([[0],
       [1]])

In [14]:
np.vstack((a, b))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [ 0],
       [ 1]])

In [15]:
c = np.arange(2).reshape(1, 2)
c

array([[0, 1]])

In [16]:
#np.vstack((a, c)) #error

### 2D

In [17]:
d = np.arange(4).reshape(2, 2)
d## 2D

array([[0, 1],
       [2, 3]])

In [18]:
np.vstack((c, d))   

array([[0, 1],
       [0, 1],
       [2, 3]])

### 3D

In [19]:
e = np.arange(24).reshape(4, 3, 2)
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [20]:
f = np.arange(6).reshape(1, 3, 2)
f

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [21]:
np.vstack((e, f)), np.vstack((e, f)).shape

(array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]],
 
        [[12, 13],
         [14, 15],
         [16, 17]],
 
        [[18, 19],
         [20, 21],
         [22, 23]],
 
        [[ 0,  1],
         [ 2,  3],
         [ 4,  5]]]),
 (5, 3, 2))

               可合并                             不可合并
    
          (2, 3) 與 (3, 3)                    (2, 3) 與 (2, 2)
    
          (2, 2) 與 (2, 2)                    (2, 2) 與 (2, 5)
    
       (1, 2, 3) 與 (4, 2, 3)              (1, 2, 3) 與 (1, 2, 2)
    
    (2, 5, 3, 2) 與 (9, 5, 3, 2)        (2, 5, 3, 2) 與 (2, 7, 3, 2)