# 增加陣列的軸數 - np.newaxis

    ndarray[:, np.newaxis] or ndarray[:,None]

In [1]:
import numpy as np

In [2]:
np.newaxis is None

True

In [3]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
x[np.newaxis, :, :], x[np.newaxis, :].shape

(array([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]]]),
 (1, 3, 5))

In [5]:
x[:, np.newaxis, :], x[:, np.newaxis, :].shape

(array([[[ 0,  1,  2,  3,  4]],
 
        [[ 5,  6,  7,  8,  9]],
 
        [[10, 11, 12, 13, 14]]]),
 (3, 1, 5))

In [6]:
x[:, None, :], x[:, None, :].shape

(array([[[ 0,  1,  2,  3,  4]],
 
        [[ 5,  6,  7,  8,  9]],
 
        [[10, 11, 12, 13, 14]]]),
 (3, 1, 5))

In [7]:
x = x.flatten()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
x[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [9]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
np.reshape(x, (1, 3, 5)) #same as x[np.newaxis, :, :]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [11]:
np.reshape(x, (1, 3, 5)) #same as x[np.newaxis, :, :]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [12]:
x = x.flatten()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.reshape(x, (-1, 1)) #same as x[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

reshape() 缺點：無法在不確定維度的情況下增加軸數