# 找出不是0的元素 - nonzero()

    np.nonzero(a)
    ndarray.nonzero()
    
    almost like np.where(a!=0)

In [1]:
import numpy as np

In [2]:
np.random.seed(49999)
a = np.random.randint(10, size=20)
a

array([7, 4, 3, 7, 0, 4, 6, 0, 7, 2, 3, 8, 1, 0, 0, 9, 2, 8, 1, 9])

In [3]:
a.nonzero()

(array([ 0,  1,  2,  3,  5,  6,  8,  9, 10, 11, 12, 15, 16, 17, 18, 19],
       dtype=int64),)

In [4]:
np.nonzero(a)

(array([ 0,  1,  2,  3,  5,  6,  8,  9, 10, 11, 12, 15, 16, 17, 18, 19],
       dtype=int64),)

In [5]:
a[np.nonzero(a)]

array([7, 4, 3, 7, 4, 6, 7, 2, 3, 8, 1, 9, 2, 8, 1, 9])

In [6]:
np.random.seed(49999)
b = np.random.randint(0, 10, size=(4,5))
b

array([[7, 4, 3, 7, 0],
       [4, 6, 0, 7, 2],
       [3, 8, 1, 0, 0],
       [9, 2, 8, 1, 9]])

In [7]:
b.nonzero() #2d index

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 3, 4, 0, 1, 2, 0, 1, 2, 3, 4], dtype=int64))

In [8]:
b[b.nonzero()]

array([7, 4, 3, 7, 4, 6, 7, 2, 3, 8, 1, 9, 2, 8, 1, 9])