# 建立隨機亂數的陣列 - random()

In [1]:
import numpy as np

## np.random.rand() & np.random.randint()

    np.random.rand(d0, d1, ...dn)
    np.random.randint(low, high, size, dtype)

In [2]:
np.random.rand()

0.6453321035833139

In [3]:
np.random.randint(10)

0

In [4]:
np.random.rand(2, 3)

array([[0.91804875, 0.76555543, 0.17231395],
       [0.5494364 , 0.601591  , 0.98108009]])

In [5]:
np.random.randint(10, size=(2, 3))

array([[6, 4, 6],
       [5, 5, 3]])

In [6]:
np.random.randint(5, 10, size=10)

array([5, 7, 5, 8, 6, 9, 9, 7, 7, 6])

In [7]:
#(stop - start) * np.random.rand() + start 回歸分析
(10 - 5) * np.random.rand(10) + 5

array([7.69551755, 6.55717517, 8.63814878, 6.63363439, 6.7842304 ,
       9.91559896, 7.44128833, 6.34031624, 9.16387075, 9.48221118])

## np.random.seed()

    np.random.seed(seed)
    np.random模組的亂數產生器在初始化時，會使用一個整數來作爲seed
    seed不變 random出來的結果就不變

In [8]:
np.random.seed(20)

In [9]:
np.random.rand()

0.5881308010772742

In [10]:
np.random.seed(20)
np.random.rand()

0.5881308010772742

## np.random.choice()

    np.random.choice(a, size, replace=True, p)
    np.random.choice不僅可以隨機取出元素， 還可用replace來控制是否取出重複的元素

In [11]:
a = ['Python', 'Ruby', 'Java', 'C++', 'PHP']

In [12]:
np.random.seed(4002)
np.random.choice(a, 3)

array(['Java', 'Python', 'Java'], dtype='<U6')

In [13]:
np.random.seed(4002)
np.random.choice(a, 3)

array(['Java', 'Python', 'Java'], dtype='<U6')

In [14]:
np.random.seed(4002)
np.random.choice(a, 20, p=[0.75, 0.05, 0.05, 0.05, 0.1]) #各個元素的權重
# p的總和 = 1

array(['Python', 'Java', 'C++', 'Python', 'Python', 'Python', 'Python',
       'Python', 'Python', 'Python', 'Java', 'PHP', 'Python', 'Java',
       'Python', 'Python', 'Python', 'Python', 'Python', 'Python'],
      dtype='<U6')

In [15]:
np.random.seed(4002)
np.random.choice(a, 20, p=[0.75, 0.05, 0.05, 0.05, 0.1]) #各個元素的權重
# p的總和 = 1

array(['Python', 'Java', 'C++', 'Python', 'Python', 'Python', 'Python',
       'Python', 'Python', 'Python', 'Java', 'PHP', 'Python', 'Java',
       'Python', 'Python', 'Python', 'Python', 'Python', 'Python'],
      dtype='<U6')

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.random.shuffle(a)
a

array([9, 2, 3, 0, 8, 1, 6, 7, 5, 4])