# 陣列排列 - sort() 與 argsort()

    np.sort() vs np.argsort()
    np.sort(a, axis=-1, kind='quicksort', order=None)：回傳值
    np.argsort(a, axis=-1, kind='quicksort', order=None)：回傳索引值
    kind: quicksort, mergesort, heapsort

In [1]:
import numpy as np

## 1D

In [2]:
a = np.random.randint(0, 100, size=20)
a

array([12, 20,  0, 28, 29, 54, 73, 11,  6,  3, 77, 93,  9, 61, 76, 97,  4,
       98, 66, 13])

In [3]:
np.sort(a)

array([ 0,  3,  4,  6,  9, 11, 12, 13, 20, 28, 29, 54, 61, 66, 73, 76, 77,
       93, 97, 98])

In [4]:
a = np.array([1, 3, 2])
np.argsort(a)

array([0, 2, 1], dtype=int64)

## 2D

In [5]:
b = np.random.randint(0, 100, size=20).reshape(4, 5)
b

array([[39, 10, 43, 14,  5],
       [48, 29, 89, 78, 14],
       [41,  0, 65, 36, 84],
       [82, 82, 54, 98, 27]])

In [6]:
np.sort(b)

array([[ 5, 10, 14, 39, 43],
       [14, 29, 48, 78, 89],
       [ 0, 36, 41, 65, 84],
       [27, 54, 82, 82, 98]])

In [7]:
np.argsort(b)

array([[4, 1, 3, 0, 2],
       [4, 1, 0, 3, 2],
       [1, 3, 0, 2, 4],
       [4, 2, 0, 1, 3]], dtype=int64)

In [8]:
np.sort(b, axis=0)

array([[39,  0, 43, 14,  5],
       [41, 10, 54, 36, 14],
       [48, 29, 65, 78, 27],
       [82, 82, 89, 98, 84]])

In [9]:
np.argsort(b, axis=0)

array([[0, 2, 0, 0, 0],
       [2, 0, 3, 2, 1],
       [1, 1, 2, 1, 3],
       [3, 3, 1, 3, 2]], dtype=int64)

## 3D

In [10]:
c = np.random.randint(0, 100, size=40).reshape(2, 4, 5)
c

array([[[64, 56, 70, 70, 60],
        [60, 94, 44, 40, 86],
        [76, 66, 22, 65, 17],
        [86, 81, 17, 40, 65]],

       [[ 1, 60, 32, 19,  8],
        [63, 79, 98, 81, 23],
        [23, 96, 42, 30, 53],
        [90, 47, 95, 13, 24]]])

In [11]:
np.sort(c)

array([[[56, 60, 64, 70, 70],
        [40, 44, 60, 86, 94],
        [17, 22, 65, 66, 76],
        [17, 40, 65, 81, 86]],

       [[ 1,  8, 19, 32, 60],
        [23, 63, 79, 81, 98],
        [23, 30, 42, 53, 96],
        [13, 24, 47, 90, 95]]])

In [12]:
np.sort(c, axis=0)

array([[[ 1, 56, 32, 19,  8],
        [60, 79, 44, 40, 23],
        [23, 66, 22, 30, 17],
        [86, 47, 17, 13, 24]],

       [[64, 60, 70, 70, 60],
        [63, 94, 98, 81, 86],
        [76, 96, 42, 65, 53],
        [90, 81, 95, 40, 65]]])

In [13]:
np.argsort(c, axis=0)

array([[[1, 0, 1, 1, 1],
        [0, 1, 0, 0, 1],
        [1, 0, 0, 1, 0],
        [0, 1, 0, 1, 1]],

       [[0, 1, 0, 0, 0],
        [1, 0, 1, 1, 0],
        [0, 1, 1, 0, 1],
        [1, 0, 1, 0, 0]]], dtype=int64)

## order用法

In [14]:
values = [('Catherine', 1, 8.6), ('Bob', 12, 7.6), ('Alice', 25, 9.6), 
          ('David', 10, 7.6)]
dt = [('name', 'S10'), ('ID', int), ('score', float)]

In [15]:
a = np.array(values, dtype=dt)

In [16]:
np.sort(a, order='name')

array([(b'Alice', 25, 9.6), (b'Bob', 12, 7.6), (b'Catherine',  1, 8.6),
       (b'David', 10, 7.6)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [17]:
np.sort(a, order='ID')

array([(b'Catherine',  1, 8.6), (b'David', 10, 7.6), (b'Bob', 12, 7.6),
       (b'Alice', 25, 9.6)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [18]:
np.sort(a, order='score')

array([(b'Bob', 12, 7.6), (b'David', 10, 7.6), (b'Catherine',  1, 8.6),
       (b'Alice', 25, 9.6)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [19]:
np.argsort(a, order='score')

array([1, 3, 0, 2], dtype=int64)

In [20]:
np.sort(a, order=['score', 'ID'])

array([(b'David', 10, 7.6), (b'Bob', 12, 7.6), (b'Catherine',  1, 8.6),
       (b'Alice', 25, 9.6)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [21]:
np.sort(a, order=['score', 'ID'])

array([(b'David', 10, 7.6), (b'Bob', 12, 7.6), (b'Catherine',  1, 8.6),
       (b'Alice', 25, 9.6)],
      dtype=[('name', 'S10'), ('ID', '<i4'), ('score', '<f8')])

In [22]:
d = np.random.randint(0, 100, size=10)
d

array([89, 59, 83, 27, 97,  4, 92,  8, 16, 68])

In [23]:
np.sort(d)

array([ 4,  8, 16, 27, 59, 68, 83, 89, 92, 97])

d并沒有改變

In [24]:
d

array([89, 59, 83, 27, 97,  4, 92,  8, 16, 68])

In [25]:
d.sort()
d

array([ 4,  8, 16, 27, 59, 68, 83, 89, 92, 97])