# 陣列轉置 - transpose()

    np.transpose(a, axes=None)
    
    axes是axis的複數
    axes=(1, 0, 2)是指將第0軸與第1軸對調

In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [4]:
np.transpose(a, (1, 0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [5]:
b = np.arange(6)
b, b.shape

(array([0, 1, 2, 3, 4, 5]), (6,))

In [6]:
np.transpose(b)

array([0, 1, 2, 3, 4, 5])

In [7]:
b = b.reshape(1, 6)
b, b.shape

(array([[0, 1, 2, 3, 4, 5]]), (1, 6))

In [8]:
b.transpose(), b.shape

(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]),
 (1, 6))

In [9]:
c = np.arange(24).reshape(4, 3, 2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

沒有設定axes, 就代表自動代入(2, 1, 0)
i.e. (2, 7, 5) -> (5, 7, 2)

In [10]:
np.transpose(c), np.transpose(c).shape

(array([[[ 0,  6, 12, 18],
         [ 2,  8, 14, 20],
         [ 4, 10, 16, 22]],
 
        [[ 1,  7, 13, 19],
         [ 3,  9, 15, 21],
         [ 5, 11, 17, 23]]]),
 (2, 3, 4))

In [11]:
np.transpose(c, axes=(1, 0, 2)), np.transpose(c, axes=(1, 0, 2)).shape

(array([[[ 0,  1],
         [ 6,  7],
         [12, 13],
         [18, 19]],
 
        [[ 2,  3],
         [ 8,  9],
         [14, 15],
         [20, 21]],
 
        [[ 4,  5],
         [10, 11],
         [16, 17],
         [22, 23]]]),
 (3, 4, 2))

In [12]:
c.transpose(1, 0, 2)

array([[[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]],

       [[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]],

       [[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]]])

In [13]:
c.transpose(1, 0, 2).shape

(3, 4, 2)

In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [16]:
b

array([[0, 1, 2, 3, 4, 5]])

In [17]:
b.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [19]:
c.T

array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])

In [20]:
a.transpose().shape == a.T.shape

True

In [21]:
b.transpose().shape == b.T.shape

True

In [22]:
c.transpose().shape == c.T.shape

True