# 找出符合條件的元素 - where()

    np.where(condition, x, y)
    回傳其位置

## 用法一：只指定條件式

In [1]:
import numpy as np

In [2]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [3]:
np.where(a < 10)

(array([6, 7, 8, 9], dtype=int64),)

In [4]:
a[np.where(a < 10)]

array([8, 6, 4, 2])

In [5]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.where(a % 2 == 0)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 2, 0, 2, 0, 2], dtype=int64))

In [7]:
a[np.where(a % 2 == 0)]

array([ 0,  2,  4,  6,  8, 10])

## 用法二：在條件式後面加入x、y參數

In [8]:
np.where(a%2==0, 'even', 'odd')

array([['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd']], dtype='<U4')

In [9]:
#np.where(a%2==0, 'even') #error #一定要有x, y參數

In [10]:
b = np.reshape(a, (3, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
c = b ** 2
c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [12]:
np.where(b%2==0, b, c)

array([[  0,   1,   2,   9],
       [  4,  25,   6,  49],
       [  8,  81,  10, 121]])