# 計算元素平均值 - average() 與 mean()

## np.average

    np.average(a, axis=None, weights=None, returned=False)

In [1]:
import numpy as np

In [2]:
a = np.array([33, 44, 54, 23, 25, 55, 32, 76])

In [3]:
np.average(a)

42.75

In [4]:
a = a.reshape(2, 4)
a

array([[33, 44, 54, 23],
       [25, 55, 32, 76]])

In [5]:
np.average(a)

42.75

In [6]:
np.average(a, axis=0)

array([29. , 49.5, 43. , 49.5])

In [7]:
np.average(a, axis=1)

array([38.5, 47. ])

In [8]:
b = np.random.rand(24).reshape(2, 3, 4)
b

array([[[0.59309639, 0.52158142, 0.01594766, 0.75675067],
        [0.1184406 , 0.35816205, 0.67772294, 0.65030687],
        [0.43285368, 0.20894846, 0.89453204, 0.09683136]],

       [[0.19529002, 0.08029832, 0.27567252, 0.08290602],
        [0.78481764, 0.75041295, 0.13352859, 0.72275987],
        [0.87781684, 0.93121157, 0.65637253, 0.51371647]]])

In [9]:
np.average(b, axis=0)

array([[0.39419321, 0.30093987, 0.14581009, 0.41982834],
       [0.45162912, 0.5542875 , 0.40562576, 0.68653337],
       [0.65533526, 0.57008002, 0.77545229, 0.30527392]])

In [10]:
np.average(b, axis=1)

array([[0.38146356, 0.36289731, 0.52940088, 0.5012963 ],
       [0.61930817, 0.58730762, 0.35519121, 0.43979412]])

In [11]:
np.average(b, axis=2)

array([[0.47184403, 0.45115811, 0.40829138],
       [0.15854172, 0.59787976, 0.74477935]])

In [12]:
a = a.flatten()

In [13]:
w = np.array([0.1, 0.05, 0.2, 0.0, 0.0, 0.4, 0.2, 0.05])

In [14]:
np.average(a, weights=w) #(33*0.1 + 44*0.05 + ....)

48.5

In [15]:
w2 = np.array([0.2, 0.8])

In [16]:
a = a.reshape(2, 4)
a

array([[33, 44, 54, 23],
       [25, 55, 32, 76]])

In [17]:
np.average(a, axis=0, weights=w2)

array([26.6, 52.8, 36.4, 65.4])

In [18]:
np.average(a, returned=True)

(42.75, 8.0)

In [19]:
a = a.flatten()
a

array([33, 44, 54, 23, 25, 55, 32, 76])

In [21]:
w

array([0.1 , 0.05, 0.2 , 0.  , 0.  , 0.4 , 0.2 , 0.05])

In [22]:
np.average(a, weights=w, returned=True)

(48.5, 1.0)

In [23]:
np.random.seed(1)