# Basic mathematical functions

## 四則運算

    np.add(x1, x2, ...)

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4])

In [3]:
b = np.array([20, 4, 16, 10, 13])

In [4]:
a + b

array([20,  5, 18, 13, 17])

In [5]:
a + 4

array([4, 5, 6, 7, 8])

In [6]:
np.add(a, b)

array([20,  5, 18, 13, 17])

In [7]:
np.add(a, 4)

array([4, 5, 6, 7, 8])

In [8]:
a - b

array([-20,  -3, -14,  -7,  -9])

In [9]:
b - a

array([20,  3, 14,  7,  9])

In [10]:
a - 4

array([-4, -3, -2, -1,  0])

In [11]:
np.subtract(a, b)

array([-20,  -3, -14,  -7,  -9])

In [12]:
np.subtract(a, 4)

array([-4, -3, -2, -1,  0])

In [13]:
a * b

array([ 0,  4, 32, 30, 52])

In [14]:
a * 2

array([0, 2, 4, 6, 8])

In [15]:
np.multiply(a, b)

array([ 0,  4, 32, 30, 52])

In [16]:
np.multiply(a, 2)

array([0, 2, 4, 6, 8])

In [17]:
b / a

C:\Users\JorJor\AppData\Local\Temp/ipykernel_16240/1491818542.py:1: RuntimeWarning: divide by zero encountered in true_divide
  b / a


array([       inf, 4.        , 8.        , 3.33333333, 3.25      ])

In [18]:
b / 2

array([10. ,  2. ,  8. ,  5. ,  6.5])

In [19]:
b / 3

array([6.66666667, 1.33333333, 5.33333333, 3.33333333, 4.33333333])

In [20]:
np.divide(b, a)

C:\Users\JorJor\AppData\Local\Temp/ipykernel_16240/2227768009.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(b, a)


array([       inf, 4.        , 8.        , 3.33333333, 3.25      ])

In [21]:
np.divide(b, 2)

array([10. ,  2. ,  8. ,  5. ,  6.5])

In [22]:
b // 3

array([6, 1, 5, 3, 4], dtype=int32)

In [23]:
b % 3

array([2, 1, 1, 1, 1], dtype=int32)

In [24]:
np.mod(b, 3)

array([2, 1, 1, 1, 1], dtype=int32)

In [25]:
np.divmod(b, 3)

(array([6, 1, 5, 3, 4], dtype=int32), array([2, 1, 1, 1, 1], dtype=int32))

## 次方 np.power() 與 平方根 np.sqrt()

    np.power(x, t) -> x ^ t
    np.sqrt(x)

In [26]:
np.power(2, 3)

8

In [27]:
2**3

8

In [28]:
a = np.arange(1, 11, 1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
b = np.array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

In [30]:
np.power(a, b)

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100], dtype=int32)

In [31]:
a ** b

array([  1,   4,   3,  16,   5,  36,   7,  64,   9, 100], dtype=int32)

In [32]:
np.sqrt(2)

1.4142135623730951

In [33]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

## 三角函數

    np.sin()
    np.cos()
    np.tan()
    np.arcsin()
    np.arccos()
    np.arctan()

In [34]:
np.sin(0)

0.0

In [35]:
np.cos(0)

1.0

In [36]:
np.tan(0)

0.0

In [37]:
np.sin(np.pi/2)

1.0

In [38]:
np.cos(np.pi/2) #almost equal to 0

6.123233995736766e-17

In [39]:
np.tan(np.pi/2) #inf

1.633123935319537e+16

In [40]:
np.arcsin(0.5), np.sin(0.5235987755982989)

(0.5235987755982989, 0.5)

In [41]:
np.arccos(0.5)

1.0471975511965979

In [42]:
np.arctan(1.0)

0.7853981633974483

In [43]:
np.arcsin(-1.0)

-1.5707963267948966

In [44]:
np.arccos(-1.0)

3.141592653589793

In [45]:
np.arctan(-0.5)

-0.4636476090008061

    np.deg2rad()
    np.rad2deg()

In [46]:
np.deg2rad(120)

2.0943951023931953

In [47]:
np.rad2deg(np.pi)

180.0

## 指數函數、對數函數

    np.exp(x)
    np.log(x)
    np.log2(x)
    np.log10(x)
    np.log1p(x) = log(1 + x)

In [48]:
np.exp(1)

2.718281828459045

In [49]:
np.exp(2)

7.38905609893065

In [50]:
np.exp(0)

1.0

In [51]:
np.log(np.e)

1.0

In [52]:
a = np.array([1, 2, np.e**2, 10])

In [53]:
np.log(a)

array([0.        , 0.69314718, 2.        , 2.30258509])

In [54]:
b = np.array([1, 2, 4, 7])

In [55]:
np.log2(b)

array([0.        , 1.        , 2.        , 2.80735492])

In [56]:
c = np.array([1, 10, 20, 100])

In [57]:
np.log10(c)

array([0.     , 1.     , 1.30103, 2.     ])

In [58]:
np.log1p(a)

array([0.69314718, 1.09861229, 2.12692801, 2.39789527])

In [59]:
np.log(2)/np.log(4) #log2(4)

0.5

In [60]:
np.log(9)/np.log(3) #log3(9)

2.0

## 雙曲函數

    np.sinh(x)
    np.cosh(x)
    np.tanh(x)
    np.arcsinh(x)
    np.arccosh(x)
    np.arctanh(x)
    
    sinh(x) = (e^(x) - e^(-x))/2
    cosh(x) = (e^(x) + e^(-x))/2
    tanh(x) = sinh(x)/cosh(x)

In [61]:
np.sinh(2)

3.6268604078470186

In [62]:
np.cosh(2)

3.7621956910836314

In [63]:
np.tanh(2)

0.9640275800758169

In [64]:
np.arccosh(1)

0.0

In [65]:
np.arctanh(0.7)

0.8673005276940532

## 取近似值

    np.floor(x): 向下取值，最接近x并且最大的整數
    np.trunc(x): int(x)
    np.ceil(x): 向上取值，最接近x并且最小的整數
    np.round(x): 四舍六入五成雙 == np.arouns(x)
    np.rint(x)
    np.fix(x)

In [66]:
a = np.arange(-1.8, 2, 0.4)
a

array([-1.8, -1.4, -1. , -0.6, -0.2,  0.2,  0.6,  1. ,  1.4,  1.8])

In [67]:
np.floor(a)

array([-2., -2., -1., -1., -1.,  0.,  0.,  1.,  1.,  1.])

In [68]:
np.trunc(a)

array([-1., -1., -0., -0., -0.,  0.,  0.,  1.,  1.,  1.])

In [69]:
np.ceil(a)

array([-1., -1., -0., -0., -0.,  1.,  1.,  2.,  2.,  2.])

In [70]:
np.round(a) #same as np.around(a)

array([-2., -1., -1., -1., -0.,  0.,  1.,  1.,  1.,  2.])

In [71]:
np.around(a) #same as np.round(a)

array([-2., -1., -1., -1., -0.,  0.,  1.,  1.,  1.,  2.])

In [72]:
np.rint(a)

array([-2., -1., -1., -1., -0.,  0.,  1.,  1.,  1.,  2.])

In [73]:
np.fix(a)

array([-1., -1., -0., -0., -0.,  0.,  0.,  1.,  1.,  1.])

## 絕對值

    np.absolute()
    np.fabs()
    之間差別在於 前者可傳入complex作爲複數，後者不行

In [74]:
a = -2.5

In [75]:
np.absolute(a)

2.5

In [76]:
np.fabs(a)

2.5

In [77]:
np.fabs(a)

2.5

In [78]:
np.abs(b) #same as np.absolute

array([1, 2, 4, 7])

In [79]:
#np.fabs(b) #error

In [80]:
c = np.array([-1, 2, -8, 12, 1+2j])

In [81]:
np.abs(c)

array([ 1.        ,  2.        ,  8.        , 12.        ,  2.23606798])

In [82]:
np.abs(c)

array([ 1.        ,  2.        ,  8.        , 12.        ,  2.23606798])