# 計算卷積 - convolve()

    np.convolve(a, v, mode='full')
    mode:full, same, valid

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4, 5])
v = np.array([0.2, 0.8])

In [3]:
np.convolve(a, v, mode='full')

array([0. , 0.2, 1.2, 2.2, 3.2, 4.2, 4. ])

In [4]:
np.convolve(a, v, mode='same')

array([0. , 0.2, 1.2, 2.2, 3.2, 4.2])

In [5]:
np.convolve(a, v, mode='valid')

array([0.2, 1.2, 2.2, 3.2, 4.2])