## 計算共變異數 - cov()

    np.cov(m, y=None, rowvar=True, bias=False, ddof=None, fweights=None,
    aweights=None)
    
    

    X = {x1, x2, x3, ....., xn}
    Y = {y1, y2, y3, ....., yn}
    
    Sxy = (1/n) * np.sum((xi - x')(yi - y'))
    
    if x == y, Varx = (1/n) * np.sum((xi - x')^2)

In [1]:
import numpy as np

In [2]:
a = np.array([[10, 5, 2, 4, 9, 3, 2], [10, 2, 8, 3, 7, 4, 1]])

In [3]:
np.cov(a) #對角綫不看 6.666666667是他們的共變異數

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [4]:
c = np.array([3, 2, 1, 5, 7, 2, 1])

In [5]:
np.cov(a, c) 
#對角綫不看 是各自的變異數
#6.66666667是第一組跟第二組的共變異數
#4.66666667是第一組跟第三組的共變異數
#4.66666667是第二組跟第三組的共變異數

array([[10.66666667,  6.66666667,  4.66666667],
       [ 6.66666667, 11.33333333,  1.66666667],
       [ 4.66666667,  1.66666667,  5.        ]])

In [6]:
np.cov(c, a) 

array([[ 5.        ,  4.66666667,  1.66666667],
       [ 4.66666667, 10.66666667,  6.66666667],
       [ 1.66666667,  6.66666667, 11.33333333]])

    bias=False 分母為1/(n-1) : 求樣本共變異數
    bias=True 分母為1/n

In [7]:
np.cov(a, bias=False)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [8]:
np.cov(a, bias=True)

array([[9.14285714, 5.71428571],
       [5.71428571, 9.71428571]])

    ddof=1 or ddof=None 分母為1/(n-1) : 求樣本共變異數
    ddof=0 分母為1/n

In [9]:
np.cov(a, ddof=None)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [10]:
np.cov(a, ddof=1)

array([[10.66666667,  6.66666667],
       [ 6.66666667, 11.33333333]])

In [11]:
np.cov(a, ddof=0)

array([[9.14285714, 5.71428571],
       [5.71428571, 9.71428571]])

    In pratice, (ddof=1) == (bias=False)
    當ddof設定None, bias會被覆蓋
    建議一律使用ddof就好

In [12]:
#fweights = frequency weights
#可以指定將重要的觀測值重複計算幾次
a

array([[10,  5,  2,  4,  9,  3,  2],
       [10,  2,  8,  3,  7,  4,  1]])

In [13]:
fweights = np.array([1, 2, 2, 1, 1, 1, 1])

In [14]:
np.cov(a, fweights=fweights)

array([[ 9.   ,  3.875],
       [ 3.875, 10.75 ]])

    以上可理解為
    [[10, 5, 5, 2, 2, 4, 9, 3, 2]
     [10, 2, 2, 8, 8, 3, 7, 4, 1]]

In [15]:
#aweights = array of weights
#aweights.sum() == 1
aweights = np.array([0.1, 0.2, 0.2, 0.2, 0.1, 0.1, 0.1])

In [16]:
np.cov(a, aweights=aweights)

array([[ 8.61904762,  3.83333333],
       [ 3.83333333, 10.66666667]])

    np.cov()最經典是在ml做PCA(Principal components analysis)
    面對一大推Feature就可簡化複雜度