# 點積運算 - dot()

    np.dot(a, b, out=None)

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2])
b = np.array([4, 3])

In [3]:
np.dot(a, b) # 1*4 + 2*3

10

In [4]:
np.dot(4, 5) # same as 4*5

20

In [5]:
e = np.matrix([1, 2])
f1 = np.matrix([4, 3])

In [6]:
#np.dot(e, f1) #error

In [7]:
f2 = np.matrix([[4], [3]])

In [8]:
np.dot(e, f2)

matrix([[10]])

In [9]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])

In [10]:
np.dot(a, b)
# 1*4+2*2 1*3+2*1 
# 3*4+4*2 3*3+4*1

array([[ 8,  5],
       [20, 13]])

In [11]:
c = np.arange(9).reshape(3, 3)
d = np.ones((3, 3))

In [12]:
np.dot(c, d)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [13]:
a = np.arange(12).reshape(3, 4)
b = np.arange(16).reshape(4, 4)

In [14]:
#np.dot(a, b) #error

matrix 回傳的不是 ndarray, 因此他們不同