# 計算矩陣的｢反矩陣｣ - linalg.inv()

    np.linalg.inv(a)

In [1]:
import numpy as np

In [2]:
a = np.random.randint(-9, 10, size=(2, 2))
a

array([[-2, -4],
       [-9,  8]])

In [3]:
np.linalg.inv(a)

array([[-0.15384615, -0.07692308],
       [-0.17307692,  0.03846154]])

In [4]:
np.dot(a, np.linalg.inv(a))

array([[1.00000000e+00, 2.77555756e-17],
       [0.00000000e+00, 1.00000000e+00]])

In [5]:
b = np.random.randint(-10, 10, size=(3, 3))
b

array([[ 7,  0, -8],
       [ 0,  0,  9],
       [-9, -8,  7]])

In [6]:
np.linalg.inv(b)

array([[ 0.14285714,  0.12698413, -0.        ],
       [-0.16071429, -0.04563492, -0.125     ],
       [ 0.        ,  0.11111111,  0.        ]])

In [7]:
np.dot(b, np.linalg.inv(b))

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.55111512e-17, 1.00000000e+00]])

以上除了對角都爲一， 其餘都趨近于0，因此為3x3的單位矩陣