# 計算矩陣的 determinant - linalg.det()

    linalg:Linear Algebra
    determinant:det(A) or |A|
    
    np.linalg.det(a)
    a.shape must be N x N

In [1]:
import numpy as np
import numpy.linalg as LA

In [2]:
a = np.array([[2, 3], [4, -1]])
a

array([[ 2,  3],
       [ 4, -1]])

In [3]:
LA.det(a)

-14.000000000000004

In [4]:
d = np.random.randint(-5, 6, size=(3, 3, 3))
d

array([[[-5,  2,  1],
        [ 0, -2, -2],
        [-1, -1,  2]],

       [[-4, -3, -2],
        [-5, -3, -1],
        [ 4,  2,  5]],

       [[-2,  3,  3],
        [-5, -2,  0],
        [-5, -4,  5]]])

In [5]:
LA.det(d)

array([ 32., -15., 125.])