# 計算矩陣的｢特徵值｣與｢特徵向量｣ - linalg.eig()

    eigenvalue:特徵值
    eigenvector:特徵向量
    
    np.linalg.eig(a)

In [2]:
import numpy as np
import numpy.linalg as LA

In [4]:
a = np.array([[1, 0], [0, 2]])
a

array([[1, 0],
       [0, 2]])

In [6]:
LA.eig(a) #eigenvalue, eigenvector

(array([1., 2.]),
 array([[1., 0.],
        [0., 1.]]))

In [7]:
b = np.array([[2, 5], [3, -8]])
b

array([[ 2,  5],
       [ 3, -8]])

In [8]:
LA.eig(b)

(array([ 3.32455532, -9.32455532]),
 array([[ 0.96665615, -0.40390206],
        [ 0.25607791,  0.91480224]]))

In [9]:
c = np.random.randint(-10, 10, size=(3, 3))

In [10]:
w, v = LA.eig(c)

In [11]:
w

array([-4.16312894+7.46825292j, -4.16312894-7.46825292j,
       -7.67374212+0.j        ])

In [12]:
v

array([[ 0.7138939 +0.j        ,  0.7138939 -0.j        ,
         0.00387114+0.j        ],
       [ 0.29105502-0.11316916j,  0.29105502+0.11316916j,
        -0.78899729+0.j        ],
       [-0.37207957-0.50437289j, -0.37207957+0.50437289j,
         0.61438448+0.j        ]])

In [14]:
d = np.random.randint(-10, 10, size=(3, 3, 3))
d

array([[[  1,  -8,  -1],
        [  7,   2,  -9],
        [ -9,   8,  -1]],

       [[ -5,   9, -10],
        [ -6,   7,  -6],
        [  9, -10,   9]],

       [[  2,  -2,  -9],
        [ -8,   1,  -3],
        [  1,  -1,   8]]])

In [15]:
w, v = LA.eig(d)

In [16]:
w

array([[-4.72652118 +0.j        ,  3.36326059+11.76781726j,
         3.36326059-11.76781726j],
       [ 5.38371333 +5.95914544j,  5.38371333 -5.95914544j,
         0.23257334 +0.j        ],
       [-3.00915891 +0.j        ,  7.00457946 +3.01523665j,
         7.00457946 -3.01523665j]])

In [17]:
v

array([[[ 0.60176394+0.j        , -0.04300273+0.44771062j,
         -0.04300273-0.44771062j],
        [ 0.34044154+0.j        ,  0.68849229+0.j        ,
          0.68849229-0.j        ],
        [ 0.72248164+0.j        , -0.13773484-0.55200856j,
         -0.13773484+0.55200856j]],

       [[ 0.74410961+0.j        ,  0.74410961-0.j        ,
          0.37206234+0.j        ],
        [ 0.33119672+0.18154257j,  0.33119672-0.18154257j,
          0.77829984+0.j        ],
        [-0.47458504-0.28003743j, -0.47458504+0.28003743j,
          0.50578551+0.j        ]],

       [[-0.43494154+0.j        ,  0.49874276+0.39644043j,
          0.49874276-0.39644043j],
        [-0.89946955+0.j        , -0.66625231+0.j        ,
         -0.66625231-0.j        ],
        [-0.04219469+0.j        ,  0.00354095-0.38753834j,
          0.00354095+0.38753834j]]])