# 網格陣列 - meshgrid()

    np.meshgrid(x1, x2, ..., indexing='xy', sparse=False, copy=True)

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])
b = np.array([4, 0])

In [3]:
aa, bb = np.meshgrid(a, b)

In [4]:
aa

array([[0, 1, 2],
       [0, 1, 2]])

In [5]:
bb

array([[4, 4, 4],
       [0, 0, 0]])

In [6]:
aa2, bb2 = np.meshgrid(a, b, indexing='xy')

In [7]:
aa2

array([[0, 1, 2],
       [0, 1, 2]])

In [8]:
bb2

array([[4, 4, 4],
       [0, 0, 0]])

In [9]:
aa3, bb3 = np.meshgrid(a, b, indexing='ij') # In pratice,'ij' == 'yx'

In [10]:
aa3

array([[0, 0],
       [1, 1],
       [2, 2]])

In [11]:
bb3

array([[4, 0],
       [4, 0],
       [4, 0]])

In [12]:
aa4, bb4 = np.meshgrid(a, b, sparse=True)

In [13]:
aa4

array([[0, 1, 2]])

In [14]:
bb4

array([[4],
       [0]])