# 計算標準差、變異數 - std()、var()

## 計算標準差 - std()

    np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)
    ddof : can control the n of std
    
    
    s : standard deviation
    x': mean 
    s = np.sqrt((1/n) * np.sum((xi - x')^2))

In [1]:
import numpy as np

In [2]:
a = np.random.rand(10)
a

array([0.77255122, 0.48848897, 0.96417211, 0.38314568, 0.98466659,
       0.49351809, 0.27342223, 0.84658268, 0.02193054, 0.23657774])

In [3]:
np.std(a)

0.3140449189261954

In [4]:
b = np.random.rand(2, 3, 4)
b

array([[[0.02137413, 0.67000693, 0.9241003 , 0.16537402],
        [0.92663776, 0.05113922, 0.4384407 , 0.06281252],
        [0.14727726, 0.27905977, 0.62053111, 0.0069834 ]],

       [[0.63620653, 0.87324789, 0.68634265, 0.92791538],
        [0.40984764, 0.98574801, 0.46989147, 0.7780029 ],
        [0.71958995, 0.57928019, 0.73232145, 0.17948006]]])

In [5]:
np.std(b, axis=0)

array([[0.3074162 , 0.10162048, 0.11887882, 0.38127068],
       [0.25839506, 0.4673044 , 0.01572539, 0.35759519],
       [0.28615635, 0.15011021, 0.05589517, 0.08624833]])

In [6]:
np.std(b)

0.3204619190025707

In [7]:
np.std(b, ddof=1) 
#1/n -> 1/(n-1)
#貝索校正(Bessel's correction)

0.3273543616925033

## 計算變異數 - var()

    np.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)
    
    var = np.sqrt(std)

In [8]:
x = np.array([10, 20, 12, 0, 3, 5])

In [9]:
np.var(a)

0.09862421110336064

其餘用法與std()相同