# 計算標準差 - std()

    np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)
    ddof : can control the n of std
    
    
    s : standard deviation
    x': mean 
    s = np.sqrt(np.sum((xi - x')^2)/n)

In [1]:
import numpy as np

In [2]:
a = np.random.rand(10)
a

array([0.53733044, 0.59081369, 0.73914737, 0.96926611, 0.16411687,
       0.89720994, 0.57388033, 0.43865924, 0.49793853, 0.59678938])

In [3]:
np.std(a)

0.21799000851750966

In [4]:
b = np.random.rand(2, 3, 4)
b

array([[[0.76748822, 0.77684687, 0.71730878, 0.78856261],
        [0.34640301, 0.46853097, 0.76433827, 0.47437283],
        [0.94444639, 0.97027875, 0.462011  , 0.651048  ]],

       [[0.75260363, 0.31789041, 0.05937933, 0.29388538],
        [0.66002627, 0.68002925, 0.00640116, 0.1687039 ],
        [0.42489969, 0.21990882, 0.80562175, 0.39576642]]])

In [5]:
np.std(b, axis=0)

array([[0.00744229, 0.22947823, 0.32896473, 0.24733862],
       [0.15681163, 0.10574914, 0.37896855, 0.15283446],
       [0.25977335, 0.37518496, 0.17180538, 0.12764079]])

In [6]:
np.std(b)

0.26732574478825866

In [7]:
np.std(b, ddof=1) 
#1/n -> 1/(n-1)
#貝索校正(Bessel's correction)

0.273075343309142

# 計算變異數 - var()

    np.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)
    
    var = np.sqrt(std)

In [8]:
x = np.array([10, 20, 12, 0, 3, 5])

In [9]:
np.var(a)

0.047519643813463935

其餘用法與std()相同